-- Migration: rename finance_anomaly_flags → agent_anomaly_flags
-- Rationale: the table is owned by the Agents domain; the finance_ prefix
-- was a naming accident. All write paths and the DDL live in src/lib/agents/.
-- The finance anomalies UI consumes the table read-only via /api/agents/anomalies.
--
-- On production, finance_anomaly_flags was created by runtime DDL in
-- src/lib/agents/ before the code was migration-managed. On a fresh
-- shadow DB it doesn't exist, so the plain RENAME failed P1014. Use
-- IF EXISTS so shadow-DB replay skips the rename cleanly; production
-- behavior unchanged.
ALTER TABLE IF EXISTS finance_anomaly_flags RENAME TO agent_anomaly_flags;
