'use client';
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextValue {
  language: Language;
  isRTL: boolean;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  /** Translate by the English label string — use in layouts/nav */
  tLabel: (english: string) => string;
}

/* ── Key-based translations ──────────────────────────────────────────────── */
const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.dashboard':  { en: 'Dashboard',  ar: 'لوحة التحكم' },
  'nav.analytics':  { en: 'Analytics',  ar: 'التحليلات' },
  'nav.bookings':   { en: 'Bookings',   ar: 'الحجوزات' },
  'nav.agreements': { en: 'Agreements', ar: 'العقود' },
  'nav.invoices':   { en: 'Invoices',   ar: 'الفواتير' },
  'nav.customers':  { en: 'Customers',  ar: 'العملاء' },
  'nav.vehicles':   { en: 'Vehicles',   ar: 'المركبات' },
  'nav.branches':   { en: 'Branches',   ar: 'الفروع' },
  'nav.staff':      { en: 'Staff',      ar: 'الموظفون' },
  'nav.reports':    { en: 'Reports',    ar: 'التقارير' },
  'nav.settings':   { en: 'Settings',   ar: 'الإعدادات' },
  // Actions
  'action.save':    { en: 'Save',    ar: 'حفظ' },
  'action.cancel':  { en: 'Cancel',  ar: 'إلغاء' },
  'action.edit':    { en: 'Edit',    ar: 'تعديل' },
  'action.delete':  { en: 'Delete',  ar: 'حذف' },
  'action.approve': { en: 'Approve', ar: 'موافقة' },
  'action.reject':  { en: 'Reject',  ar: 'رفض' },
  'action.submit':  { en: 'Submit',  ar: 'إرسال' },
  'action.search':  { en: 'Search',  ar: 'بحث' },
  'action.filter':  { en: 'Filter',  ar: 'تصفية' },
  'action.export':  { en: 'Export',  ar: 'تصدير' },
  'action.print':   { en: 'Print',   ar: 'طباعة' },
  'action.send':    { en: 'Send',    ar: 'إرسال' },
  'action.sign':    { en: 'Sign',    ar: 'توقيع' },
  'action.new':     { en: 'New',     ar: 'جديد' },
  'action.create':  { en: 'Create',  ar: 'إنشاء' },
  'action.close':   { en: 'Close',   ar: 'إغلاق' },
  'action.open':    { en: 'Open',    ar: 'فتح' },
  'action.view':    { en: 'View',    ar: 'عرض' },
  // Status
  'status.active':    { en: 'Active',    ar: 'نشط' },
  'status.inactive':  { en: 'Inactive',  ar: 'غير نشط' },
  'status.pending':   { en: 'Pending',   ar: 'معلق' },
  'status.approved':  { en: 'Approved',  ar: 'معتمد' },
  'status.rejected':  { en: 'Rejected',  ar: 'مرفوض' },
  'status.completed': { en: 'Completed', ar: 'مكتمل' },
  'status.cancelled': { en: 'Cancelled', ar: 'ملغى' },
  'status.draft':     { en: 'Draft',     ar: 'مسودة' },
  'status.signed':    { en: 'Signed',    ar: 'موقع' },
  'status.paid':      { en: 'Paid',      ar: 'مدفوع' },
  'status.overdue':   { en: 'Overdue',   ar: 'متأخر' },
  'status.held':      { en: 'Held',      ar: 'محتجز' },
  // Common labels
  'label.name':      { en: 'Name',      ar: 'الاسم' },
  'label.phone':     { en: 'Phone',     ar: 'الهاتف' },
  'label.email':     { en: 'Email',     ar: 'البريد الإلكتروني' },
  'label.date':      { en: 'Date',      ar: 'التاريخ' },
  'label.amount':    { en: 'Amount',    ar: 'المبلغ' },
  'label.notes':     { en: 'Notes',     ar: 'ملاحظات' },
  'label.status':    { en: 'Status',    ar: 'الحالة' },
  'label.branch':    { en: 'Branch',    ar: 'الفرع' },
  'label.vehicle':   { en: 'Vehicle',   ar: 'المركبة' },
  'label.customer':  { en: 'Customer',  ar: 'العميل' },
  'label.contract':  { en: 'Contract',  ar: 'العقد' },
  'label.reference': { en: 'Reference', ar: 'المرجع' },
  'label.total':     { en: 'Total',     ar: 'الإجمالي' },
  'label.loading':   { en: 'Loading…',  ar: '...جار التحميل' },
  // UAE specific
  'uae.emirate':    { en: 'Emirate',    ar: 'الإمارة' },
  'uae.trn':        { en: 'TRN',        ar: 'رقم التسجيل الضريبي' },
  'uae.vat':        { en: 'VAT (5%)',   ar: 'ضريبة القيمة المضافة (5%)' },
  'uae.aed':        { en: 'AED',        ar: 'درهم' },
  'uae.emirates_id':{ en: 'Emirates ID',ar: 'الهوية الإماراتية' },
  // Platform
  'platform.title':  { en: 'Smart Mobility Platform',      ar: 'منصة التنقل الذكي' },
  'platform.tagline':{ en: 'UAE Smart Transport Management', ar: 'إدارة النقل الذكي في الإمارات' },
  'platform.home':   { en: 'Fleet360 Home',          ar: 'الرئيسية' },
  // Modules
  'module.finance':      { en: 'Finance ERP',          ar: 'المالية' },
  'module.leasing':      { en: 'Vehicle Leasing',      ar: 'تأجير المركبات' },
  'module.rental':       { en: 'Rent-A-Car',           ar: 'تأجير السيارات' },
  'module.maintenance':  { en: 'Vehicle Maintenance',  ar: 'صيانة المركبات' },
  'module.fleet':        { en: 'Fleet Management',     ar: 'إدارة الأسطول' },
  'module.logistics':    { en: 'Logistics',            ar: 'اللوجستيات' },
  'module.driver':       { en: 'Driver Management',   ar: 'إدارة السائقين' },
  'module.school_bus':   { en: 'School Bus',           ar: 'حافلة مدرسية' },
  'module.incidents':    { en: 'Incidents',            ar: 'الحوادث' },
  'module.compliance':   { en: 'Compliance',           ar: 'الامتثال' },
  'module.admin':        { en: 'Admin',                ar: 'الإدارة' },
  'module.reports':      { en: 'Reports',              ar: 'التقارير' },
  'module.approvals':    { en: 'Approvals',            ar: 'الموافقات' },
  'module.bus_ops':      { en: 'Staff Transport',      ar: 'نقل الموظفين' },
  'module.sustainability':{ en: 'Sustainability & ESG', ar: 'الاستدامة والحوكمة' },
};

/* ── Arabic translations for every nav label (value-keyed) ──────────────── */
// Used by tLabel() so layouts translate labels without restructuring NAV_GROUPS
const arabicLabels: Record<string, string> = {
  // ── Group headers ─────────────────────────────────────────
  'Overview':               'نظرة عامة',
  'Sales Pipeline':         'خط المبيعات',
  'Sales Lifecycle':        'دورة حياة المبيعات',
  'Reservations':           'الحجوزات',
  'Rental Operations':      'عمليات التأجير',
  'Billing':                'الفواتير',
  'Billing & Finance':      'الفواتير والمالية',
  'Operational Billing':    'الفواتير التشغيلية',
  'Customer':               'العميل',
  'Compliance & Ops':       'الامتثال والعمليات',
  'Compliance & Analytics': 'الامتثال والتحليلات',
  'Fleet & Compliance':     'الأسطول والامتثال',
  'Management':             'الإدارة',
  'Operations':             'العمليات',
  'Work Management':        'إدارة العمل',
  'Garage':                 'المستودع',
  'Alerts & Monitoring':    'التنبيهات والمراقبة',
  'Data Masters':           'بيانات المرجع',
  'Administration':         'الإدارة العامة',
  'Receivables':            'المستحقات',
  'UAE Compliance':         'الامتثال الإماراتي',
  'Multi-Branch':           'متعدد الفروع',
  'Accounting':             'المحاسبة',
  // ── Nav item labels — Finance ─────────────────────────────
  'Dashboard':              'لوحة التحكم',
  'Analytics & BI':         'التحليلات والذكاء الاصطناعي',
  'CRM Pipeline':           'خط إدارة العملاء',
  'Invoices':               'الفواتير',
  'Recurring Invoices':     'الفواتير المتكررة',
  'Payments':               'المدفوعات',
  'Credit Notes':           'إشعارات الخصم',
  'AR Aging Report':        'تقرير استحقاق الذمم',
  'Collections & Dunning':  'التحصيل والمطالبات',
  'Payment Reminders':      'تذكيرات الدفع',
  'Security Deposits':      'الودائع الأمنية',
  'Expense Management':     'إدارة المصروفات',
  'Bank Reconciliation':    'تسوية البنك',
  'Budget vs Actual':       'الميزانية مقابل الفعلي',
  'PDC Register':           'سجل الشيكات المؤجلة',
  'Tax Engine':             'محرك الضرائب',
  'VAT Returns':            'إقرارات ضريبة القيمة المضافة',
  'VAT by Branch':          'ضريبة القيمة المضافة حسب الفرع',
  'VAT Consolidation':      'توحيد ضريبة القيمة المضافة',
  'Branch P&L':             'أرباح وخسائر الفرع',
  'Chart of Accounts':      'دليل الحسابات',
  'Journal Entries':        'قيود اليومية',
  'General Ledger':         'دفتر الأستاذ العام',
  'Fixed Assets':           'الأصول الثابتة',
  'Management Accounts':    'حسابات الإدارة',
  'Balance Sheet':          'الميزانية العمومية',
  'Corporate Tax (UAE)':    'ضريبة الشركات (الإمارات)',
  'Revenue Analysis':       'تحليل الإيرادات',
  'Budget Approvals':       'موافقات الميزانية',
  'Period Locking':         'قفل الفترة',
  'Audit Log':              'سجل المراجعة',
  // ── Nav item labels — Leasing ─────────────────────────────
  'Inquiries':              'الاستفسارات',
  'Quotations':             'عروض الأسعار',
  'Agreements':             'العقود',
  'Renewals':               'التجديدات',
  'Early Termination':      'الإنهاء المبكر',
  'Pre-Billing':            'الفوترة المسبقة',
  'Receipts':               'الإيصالات',
  'Receivables (AR)':       'الذمم المدينة',
  'Direct Debits':          'الخصم المباشر',
  'Traffic Fines':          'المخالفات المرورية',
  'Fuel Management':        'إدارة الوقود',
  'Mileage & Overage':      'الكيلومترات والزيادة',
  'Insurance':              'التأمين',
  'Documents':              'الوثائق',
  'Amendments':             'التعديلات',
  'Handover & Return':      'التسليم والإرجاع',
  'Vehicle Exchange':       'استبدال المركبة',
  'Vehicle Transfers':      'نقل المركبات',
  'Vehicle Returns':        'إرجاع المركبات',
  'Lessees':                'المستأجرون',
  'Credit Assessment':      'تقييم الائتمان',
  'Workflow & Approvals':   'سير العمل والموافقات',
  'Expiry Alerts':          'تنبيهات انتهاء الصلاحية',
  'Branches':               'الفروع',
  'Branch Management':      'إدارة الفروع',
  'Staff Management':       'إدارة الموظفين',
  // ── Nav item labels — RAC ────────────────────────────────
  'Bookings':               'الحجوزات',
  'Vehicle Availability':   'توفر المركبات',
  'Rental Agreements':      'اتفاقيات الإيجار',
  'Damage Claims':          'مطالبات الأضرار',
  'Rate Engine':            'محرك الأسعار',
  'Pricing':                'التسعير',
  'Customers':              'العملاء',
  'Document Vault':         'خزنة الوثائق',
  // ── Nav item labels — Maintenance ───────────────────────
  'Service Requests':       'طلبات الخدمة',
  'Predictive Maintenance': 'الصيانة التنبؤية',
  'Requests List':          'قائمة الطلبات',
  'Maintenance History':    'تاريخ الصيانة',
  'Approvals':              'الموافقات',
  'Analytics':              'التحليلات',
  'Garage Management':      'إدارة المستودع',
  'Submit Quote':           'تقديم عرض',
  'Work Orders':            'أوامر العمل',
  'Alert Configuration':    'إعداد التنبيهات',
  'Action Centre':          'مركز الإجراءات',
  'Garages':                'المستودعات',
  'Attachment Types':       'أنواع المرفقات',
  'Integrations':           'التكاملات',
  'Email / SMS Alerts':     'تنبيهات البريد / الرسائل',
  'Notification Rules':     'قواعد الإشعارات',
  // ── Module badge descriptions ─────────────────────────────
  'Contracts · Billing · Fleet · CRM':          'العقود · الفواتير · الأسطول · إدارة العملاء',
  'Inquiries · Quotes · Handover · Compliance': 'الاستفسارات · العروض · التسليم · الامتثال',
  'Predictive · Garage · Alerts · Analytics':   'التنبؤي · المستودع · التنبيهات · التحليلات',
  'Balance Sheet · CT · Budgets · Periods · Audit': 'الميزانية · ضريبة الشركات · الميزانيات · الفترات · المراجعة',
  // ── Nav item labels — Fleet ──────────────────────────────────
  'Masters':                  'البيانات الرئيسية',
  'Finance & Analytics':      'المالية والتحليلات',
  'Vehicle Types':            'أنواع المركبات',
  'Vehicle Master':           'سجل المركبات',
  'Lifecycle Events':         'أحداث دورة الحياة',
  'Allocations':              'التخصيصات',
  'Transfers':                'التحويلات',
  'Fuel Logs':                'سجلات الوقود',
  'TCO Analysis':             'تحليل التكلفة الإجمالية',
  // ── Nav item labels — Driver ─────────────────────────────────
  'Driver Profiles':          'ملفات السائقين',
  'Shifts':                   'الورديات',
  'Training':                 'التدريب',
  'Performance':              'الأداء',
  // ── Nav item labels — Bus Ops / Staff Transport ──────────────
  'Dispatch Board':           'لوحة التوزيع',
  'Routes':                   'المسارات',
  'Route Optimizer':          'محسّن المسارات',
  'Schedules':                'الجداول الزمنية',
  'Passengers':               'الركاب',
  'Staff Members':            'أعضاء الفريق',
  'Incidents':                'الحوادث',
  // ── Nav item labels — Compliance ─────────────────────────────
  'Salik':                    'سالك',
  'Permits':                  'التصاريح',
  // ── Nav item labels — Admin ──────────────────────────────────
  'Tenants':                  'المستأجرون',
  'Branches & Regions':       'الفروع والمناطق',
  'Billing & Subscriptions':  'الفواتير والاشتراكات',
  'Roles & Permissions':      'الأدوار والصلاحيات',
  'Users':                    'المستخدمون',
  'Workflow Management':      'إدارة سير العمل',
  'Platform Info':            'معلومات المنصة',
  'Notifications':            'الإشعارات',
  'Integrations & ERP':       'التكاملات ونظام ERP',
  'E-Signing Console':        'وحدة التوقيع الإلكتروني',
  'WhatsApp Support':         'دعم واتساب',
  'Platform Settings':        'إعدادات المنصة',
  // ── Nav item labels — Reports ────────────────────────────────
  'Fleet Utilization':        'استخدام الأسطول',
  'Maintenance Cost':         'تكلفة الصيانة',
  'Driver Performance':       'أداء السائق',
  'Scheduled Reports':        'التقارير المجدولة',
  // ── Nav item labels — School Bus (emoji-prefixed labels) ──────
  '🏫 Dashboard':             '🏫 لوحة التحكم',
  '🗺️ Routes':                '🗺️ المسارات',
  '✨ Route Optimizer':        '✨ محسّن المسارات',
  '👧 Students':              '👧 الطلاب',
  '📋 Attendance':            '📋 الحضور',
  '📅 Schedules':             '📅 الجداول الزمنية',
  '🚨 Incidents':             '🚨 الحوادث',
  // ── Nav item labels — Incidents (emoji-prefixed labels) ───────
  '🚨 Dashboard':             '🚨 لوحة التحكم',
  '🔴 Active Incidents':      '🔴 الحوادث النشطة',
  '🚑 Ambulance Fleet':       '🚑 أسطول الإسعاف',
  '📋 Incident Reports':      '📋 تقارير الحوادث',
  // ── Nav item labels — Logistics (emoji-prefixed labels) ──────
  '📊 Dashboard':             '📊 لوحة التحكم',
  '🚦 Dispatch Board':        '🚦 لوحة التوزيع',
  '🗺️ Route Optimizer':       '🗺️ محسّن المسارات',
  '📋 All Trips':             '📋 جميع الرحلات',
  '🚛 Vehicles':              '🚛 المركبات',
  '👤 Drivers':               '👤 السائقون',
  '📍 Live Tracking':         '📍 التتبع المباشر',
  '💰 Freight Quotes':        '💰 عروض الشحن',
  '📈 Analytics':             '📈 التحليلات',
  // ── Nav item labels — Sustainability ─────────────────────────
  'ESG Dashboard':            'لوحة حوكمة ESG',
  'Emission Reports':         'تقارير الانبعاثات',
  'Fleet Carbon':             'كربون الأسطول',
  'Modal Shift':              'التحول الوسيط',
  'Paperless Ops':            'عمليات بلا ورق',
  'Certifications':           'الشهادات',
  'Methodology Settings':     'إعدادات المنهجية',
  // ── Nav item labels — AI & Transport Services ────────────────
  'AI Agents':                'وكلاء الذكاء الاصطناعي',
  'AI Agent Ecosystem':       'منظومة وكلاء الذكاء الاصطناعي',
  'Operations Assistant':     'المساعد التشغيلي الذكي',
  // ── Nav Categories & Global Layout ────────────────────────
  'AI & Intelligence':      'الذكاء الاصطناعي والتحليلات',
  'Transport Services':     'خدمات النقل',
  'Live Operations':        'العمليات المباشرة',
  'Fleet & Assets':         'الأسطول والأصول',
  'Governance & ESG':       'الحوكمة والاستدامة',
  'Enterprise & Admin':     'المؤسسة والإدارة',
  'Menu Settings':          'إعدادات القائمة',
  'Hidden Modules':         'الوحدات المخفية',
  'Hide from menu':         'إخفاء من القائمة',
  'Pin sidebar (keep expanded)': 'تثبيت الشريط الجانبي',
  'Unpin sidebar':          'إلغاء تثبيت الشريط',
  'Expand sidebar':         'توسيع الشريط الجانبي',
  'Collapse sidebar':       'طي الشريط الجانبي',
  'Search...':              'بحث...',
  'Search':                 'بحث',
  'Not signed in':          'غير مسجل الدخول',
  'Home':                   'الرئيسية',
  'FLEET360':               'فليت 360',
  'Mobility platform':      'منصة التنقل الذكي',
  'Platform Admin':         'مسؤول المنصة',
  'Super Administrator':    'المشرف العام',
  // ── Module & Sub-page Labels ──────────────────────────────
  'AI agents':              'وكلاء الذكاء الاصطناعي',
  'AI platform':            'منصة الذكاء الاصطناعي',
  'AI Platform':            'منصة الذكاء الاصطناعي',
  'Predictive maintenance': 'الصيانة التنبؤية',
  'Service tickets':        'تذاكر الخدمة',
  'Staff transport':        'نقل الموظفين',
  'Staff Transportation':   'نقل الموظفين',
  'School bus':             'الحافلات المدرسية',
  'Logistics':              'اللوجستيات',
  'Vehicle leasing':        'تأجير المركبات',
  'Rent-a-car':             'تأجير السيارات',
  'Vehicle maintenance':    'صيانة المركبات',
  'Fleet management':       'إدارة الأسطول',
  'Finance ERP':            'المالية والمحاسبة',
  'Sustainability & ESG':   'الاستدامة والحوكمة',
  // ── Bus Ops / Staff Transport Pages & Groups ──────────────
  'Planning':               'التخطيط',
  'Tracking':               'التتبع',
  'Workforce':              'القوى العاملة',
  'Requests':               'الطلبات',
  'Analytics':              'التحليلات',
  'Routes':                 'المسارات',
  'Route Optimization':     'تحسين المسارات',
  'Route planner':          'مخطط المسارات',
  'Schedules':              'الجداول الزمنية',
  'Schedule Templates':     'قوالب الجداول',
  'Planning Engine':        'محرك التخطيط',
  'Route Consolidation':    'دمج المسارات',
  'Transport Calendars':    'تقاويم النقل',
  'Trip Monitor':           'مراقب الرحلات',
  'Outsource Management':   'إدارة الإسناد الخارجي',
  'SLA Monitor & Alerts':   'مراقبة اتفاقيات الخدمة',
  'Optimisation Status':    'حالة التحسين',
  'Demand forecast':        'التنبؤ بالطلب',
  'Demand Forecasting':     'التنبؤ بالطلب',
  'Live Fleet Map':         'خريطة الأسطول المباشرة',
  'Geofences':              'السياج الجغرافي',
  'Gateways':               'البوابات',
  'Passengers':             'الركاب',
  'Employees':              'الموظفون',
  'Drivers Performance':    'أداء السائقين',
  'Driver Fatigue & Rest':  'إجهاد وراحة السائقين',
  'Ad-hoc & Overtime':      'الطلبات الخاصة والعمل الإضافي',
  'Transport requests':     'طلبات النقل',
  'Incidents':              'الحوادث',
  'Cost Allocation':        'توزيع التكاليف',
  'Cost Allocation & Recharge': 'توزيع التكاليف وإعادة الفوترة',
  'ESG Carbon Footprint':   'البصمة الكربونية ESG',
  // ── KPI & Dashboard Phrases ───────────────────────────────
  'Active Routes':          'المسارات النشطة',
  "Today's Trips":          'رحلات اليوم',
  'In Progress':            'قيد التنفيذ',
  'Staff Registered':       'الموظفون المسجلون',
  'Open Incidents':         'الحوادث المفتوحة',
  'Pending Requests':       'الطلبات المعلقة',
  'Quick Actions':          'إجراءات سريعة',
  'Planning Constraints (PCE)': 'قيود التخطيط (PCE)',
  'Vehicle/Resource Optimization': 'تحسين المركبات والموارد',
  'Shift SLA Monitor':      'مراقبة اتفاقية مستوى الخدمة',
  'Driver Shifts':          'ورديات السائقين',
  'Vehicle Doc Expiry':     'صلاحية وثائق المركبة',
  'Ad-Hoc / Overtime Dispatch': 'توزيع المهام الإضافية',
  'Power BI Connector':     'رابط Power BI',
  'Multilayer GIS':         'نظم المعلومات الجغرافية',
  'Rider App (PWA)':        'تطبيق الراكب (PWA)',
  'Add Route':              'إضافة مسار',
  'New Trip':               'رحلة جديدة',
  'Register Staff':         'تسجيل موظف',
  'Log Incident':           'تسجيل حادث',
  'Manage Passengers':      'إدارة الركاب',
  'View all':               'عرض الكل',
  'No trips scheduled for today.': 'لا توجد رحلات مجدولة لليوم.',
  'No trips scheduled for today. Create one.': 'لا توجد رحلات مجدولة لليوم. إنشاء رحلة.',
  'Create one.':            'إنشاء رحلة.',
  'No open incidents':      'لا توجد حوادث مفتوحة',
  'Loading dashboard...':   'جارٍ تحميل لوحة التحكم...',
  'Real-time overview of routes, trips, passengers, and incidents.': 'نظرة عامة فورية على المسارات والرحلات والركاب والحوادث.',
  'Real-time overview of routes, trips, passengers, and incidents': 'نظرة عامة فورية على المسارات والرحلات والركاب والحوادث',
  'Author PCE rules first, then analyse and apply route consolidations. Constraints gate every apply.': 'قم بإعداد قواعد محرك القيود أولاً، ثم حلل وطبق دمج المسارات.',
  'BLOCK / WARN / PENALTY rules for plans & merges': 'قواعد المنع / التحذير / الجزاءات للخطط والدمج',
  'Analyse pairs, apply merges, history & revert': 'تحليل الأزواج وتطبيق الدمج والسجل والتراجع',
  'Runcutting / blocking / roster, plus CBA and headway rules': 'تقسيم الجولات والجدولة والمناوبات وقواعد التقاطر',
  'Sequential vehicle reuse opportunities — advisory only': 'فرص إعادة استخدام المركبات المتتالية — استشارية فقط',
  // ── Fleet & Maintenance Dashboard Phrases ─────────────────
  'Fleet Dashboard':        'لوحة تحكم الأسطول',
  'Overview of your fleet operations': 'نظرة عامة على عمليات الأسطول',
  'Total fleet size':       'إجمالي حجم الأسطول',
  'Active vehicles':        'المركبات النشطة',
  'In maintenance':         'قيد الصيانة',
  'Expiring docs (30d)':    'وثائق تنتهي قريباً (30 يوم)',
  'Fleet Health Summary':   'ملخص صحة الأسطول',
  'Vehicle Availability':   'توفر المركبات',
  'Maintenance Status':     'حالة الصيانة',
  'Compliance Status':      'حالة الامتثال',
  'Risk Heat':              'مؤشر المخاطر',
  'Top 5 highest-risk vehicles — maintenance score 0–100': 'أعلى 5 مركبات خطورة — مؤشر الصيانة 0–100',
  'No vehicle risk data available': 'لا تتوفر بيانات مخاطر للمركبات',
  'Document Expiry Alert':  'تنبيه انتهاء صلاحية الوثائق',
  'Top 5 upcoming expirations in the next 30 days': 'أهم 5 انتهاءات خلال الـ 30 يوماً القادمة',
  'No expiring documents in the next 30 days': 'لا توجد وثائق منتهية الصلاحية خلال 30 يوماً',
  'Vehicle':                'المركبة',
  'days':                   'يوم',
  'Days':                   'أيام',
  'License Plate':          'لوحة الترخيص',
  'Document Type':          'نوع الوثيقة',
  'Expiry Date':            'تاريخ الانتهاء',
  'Days Remaining':         'الأيام المتبقية',
  'Control Panel':          'لوحة التحكم',
  'Vehicle Register':       'سجل المركبات',
  'Artificial Intelligence Platform': 'منصة الذكاء الاصطناعي',
  'Fleet Management':       'إدارة الأسطول',
  'Discussion...':          'المحادثة...',
  'Discussion':             'المحادثة',
  'Employee Transportation': 'نقل الموظفين',
  'School Buses':           'الحافلات المدرسية',
  'Direct Operations':      'العمليات المباشرة',
  'Governance & Sustainability': 'الحوكمة والاستدامة',
  'Enterprise & Administration': 'المؤسسة والإدارة',
  'Car Rental':             'تأجير السيارات',
  'Leasing':                'تأجير المركبات',
  'Leasing Dashboard':      'لوحة تحكم تأجير المركبات',
  'Vehicle leasing contracts, renewals, compliance, and operational billing readiness.': 'عقود تأجير المركبات والتجديدات والامتثال والجاهزية التشغيلية للفوترة.',
  'Vehicle leasing contracts, renewals, compliance, and operational billing readiness': 'عقود تأجير المركبات والتجديدات والامتثال والجاهزية التشغيلية للفوترة',
  'Focused Leasing operations after finance and remarketing cleanup.': 'عمليات التأجير المباشرة بعد المعالجات المالية والتسويقية.',
  'Focused Leasing operations after finance and remarketing cleanup': 'عمليات التأجير المباشرة بعد المعالجات المالية والتسويقية',
  'Active contracts':       'العقود النشطة',
  'Monthly revenue':        'الإيراد الشهري',
  'Portfolio value':        'قيمة المحفظة',
  'Collection rate':        'معدل التحصيل',
  'total contracts':        'إجمالي العقود',
  'active lease run-rate':  'معدل تشغيل الإيجار النشط',
  'contracted value':       'القيمة التعاقدية',
  'finance-owned collections': 'تحصيلات إدارة المالية',
  'Overdue amount':         'المبالغ المتأخرة',
  'Unbilled charges':       'الرسوم غير المفوترة',
  'Expiring policies':      'الوثائق المنتهية',
  'Needs attention':        'تتطلب الاهتمام',
  'Ready for review':       'جاهزة للمراجعة',
  'Clear':                  'سليم',
  'Next 30 days':           'خلال 30 يوماً',
  'Inquiries':              'الاستفسارات',
  'Capture leasing demand': 'تسجيل طلبات التأجير',
  'Quotations':             'عروض الأسعار',
  'Build customer offers':  'إنشاء عروض العملاء',
  'Lease Agreements':       'عقود الإيجار',
  'Lease agreements':       'عقود الإيجار',
  'Manage active agreements': 'إدارة العقود النشطة',
  'Mileage':                'الكيلومترات',
  'Readings and overage':   'القراءات والزيادة',
  'Renewals':               'التجديدات',
  'Manage renewal pipeline': 'إدارة مسار التجديد',
  'Early Terminations':     'الإنهاء المبكر للعقد',
  'Early terminations':     'الإنهاء المبكر للعقد',
  'Early termination':      'الإنهاء المبكر',
  'Close contracts cleanly': 'إغلاق العقود وتسويتها',
  'Credit Assessments':     'التقييم الائتماني',
  'Credit assessments':     'التقييم الائتماني',
  'Risk and approval checks': 'فحوصات المخاطر والموافقات',
  'Portfolio insights':     'رؤى وتحليلات المحفظة',
  'Fleet Operations':       'عمليات الأسطول',
  'Fuel, fines, insurance, and documents': 'الوقود والمخالفات والتأمين والوثائق',
  // ── Sidebar Groups & Nav Items ─────────────────────────────
  'Sales':                  'المبيعات',
  'Contracts':              'العقود',
  'Fleet & drivers':        'الأسطول والسائقين',
  'Billing & records':      'الفواتير والسجلات',
  'Master data':            'البيانات الرئيسية',
  'Monitoring':             'المراقبة',
  'Sourcing':               'التوريد',
  'Settlement':             'التسوية',
  'Network':                'الشبكة',
  'Lead channels':          'قنوات استقطاب العملاء',
  'CRM & leads':            'إدارة علاقات العملاء والفرص',
  'Transfers':              'نقل المركبات',
  'Vehicle exchanges':      'تبديل المركبات',
  'Handover':               'التسليم والاستلام',
  'Field operations':       'العمليات الميدانية',
  'Pre-billing':            'الفوترة المسبقة',
  'Branch staff':           'موظفو الفروع',
  'Bulk import':            'استيراد مجمّع',
  'Alerts':                 'التنبيهات',
  'Students':               'الطلاب',
  'Attendance':             'الحضور والغياب',
  'Stops':                  'المحطات',
  'Attendants':             'المشرفون',
  'Driver scores':          'تقييم السائقين',
  'Fees':                   'الرسوم',
  'Intelligence':           'الذكاء والتحليل',
  'Marketplace Feed':       'سوق الشحن المباشر',
  'Jobs & Requests':        'المهام والطلبات',
  'Performance Scorecard':  'بطاقة تقييم الأداء',
  'Settlement Statements':  'كشوفات التسوية',
  'Fleet Register':         'سجل الأسطول',
  'Driver Roster':          'جدول مناوبات السائقين',
  'Compliance Vault':       'خزنة الامتثال',
  'Company Profile':        'الملف التعريفي للشركة',
  'Light':                  'نهاري',
  'Dark':                   'ليلي',
  'Sign in':                'تسجيل الدخول',
  // ── Common page phrases ───────────────────────────────────
  'Loading…':               '...جار التحميل',
  'No data found':          'لا توجد بيانات',
  'Save':                   'حفظ',
  'Cancel':                 'إلغاء',
  'Delete':                 'حذف',
  'Edit':                   'تعديل',
  'Close':                  'إغلاق',
  'Approve':                'موافقة',
  'Reject':                 'رفض',
  'Submit':                 'إرسال',
  'Export XLSX':            'تصدير XLSX',
  'New':                    'جديد',
  'Create':                 'إنشاء',
  'View':                   'عرض',
  'Back':                   'رجوع',
  'Generate Now':           'إنشاء الآن',
  'Run All Now':            'تشغيل الكل الآن',
  'Add Deduction':          'إضافة خصم',
  'Process Refund':         'معالجة الاسترداد',
  'Forfeit Deposit':        'مصادرة الوديعة',
};

// Normalized lowercase map for case-insensitive lookup
const lowerArabicMap: Record<string, string> = {};
for (const [k, v] of Object.entries(arabicLabels)) {
  lowerArabicMap[k.toLowerCase().trim()] = v;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'ar',
  isRTL: true,
  setLanguage: () => {},
  t: (key) => key,
  tLabel: (english) => english,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Default to 'ar' for Arabic-First platform experience
  const [language, setLanguageState] = useState<Language>('ar');

  useEffect(() => {
    const saved = localStorage.getItem('xlai_language') as Language | null;
    if (saved === 'ar' || saved === 'en') {
      setLanguageState(saved);
    } else {
      setLanguageState('ar');
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir  = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    localStorage.setItem('xlai_language', language);
  }, [language]);

  const setLanguage = (lang: Language) => setLanguageState(lang);

  const t = (key: string): string =>
    translations[key]?.[language] ?? translations[key]?.en ?? key;

  /** Translate by English label value — case-insensitive with punctuation trim */
  const tLabel = (english: string): string => {
    if (language !== 'ar') return english;
    if (!english || typeof english !== 'string') return english;
    const trimmed = english.trim();
    if (arabicLabels[trimmed]) return arabicLabels[trimmed];
    const lower = trimmed.toLowerCase();
    if (lowerArabicMap[lower]) return lowerArabicMap[lower];
    const stripped = lower.replace(/[:.]$/, '').trim();
    if (lowerArabicMap[stripped]) return lowerArabicMap[stripped];
    return english;
  };

  return (
    <LanguageContext.Provider value={{ language, isRTL: language === 'ar', setLanguage, t, tLabel }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
