'use client';
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextValue {
  language: Language;
  isRTL: boolean;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  /** Translate by the English label string — use in layouts/nav */
  tLabel: (english: string) => string;
}

/* ── Key-based translations ──────────────────────────────────────────────── */
const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.dashboard':  { en: 'Dashboard',  ar: 'لوحة التحكم' },
  'nav.analytics':  { en: 'Analytics',  ar: 'التحليلات' },
  'nav.bookings':   { en: 'Bookings',   ar: 'الحجوزات' },
  'nav.agreements': { en: 'Agreements', ar: 'العقود' },
  'nav.invoices':   { en: 'Invoices',   ar: 'الفواتير' },
  'nav.customers':  { en: 'Customers',  ar: 'العملاء' },
  'nav.vehicles':   { en: 'Vehicles',   ar: 'المركبات' },
  'nav.branches':   { en: 'Branches',   ar: 'الفروع' },
  'nav.staff':      { en: 'Staff',      ar: 'الموظفون' },
  'nav.reports':    { en: 'Reports',    ar: 'التقارير' },
  'nav.settings':   { en: 'Settings',   ar: 'الإعدادات' },
  // Actions
  'action.save':    { en: 'Save',    ar: 'حفظ' },
  'action.cancel':  { en: 'Cancel',  ar: 'إلغاء' },
  'action.edit':    { en: 'Edit',    ar: 'تعديل' },
  'action.delete':  { en: 'Delete',  ar: 'حذف' },
  'action.approve': { en: 'Approve', ar: 'موافقة' },
  'action.reject':  { en: 'Reject',  ar: 'رفض' },
  'action.submit':  { en: 'Submit',  ar: 'إرسال' },
  'action.search':  { en: 'Search',  ar: 'بحث' },
  'action.filter':  { en: 'Filter',  ar: 'تصفية' },
  'action.export':  { en: 'Export',  ar: 'تصدير' },
  'action.print':   { en: 'Print',   ar: 'طباعة' },
  'action.send':    { en: 'Send',    ar: 'إرسال' },
  'action.sign':    { en: 'Sign',    ar: 'توقيع' },
  'action.new':     { en: 'New',     ar: 'جديد' },
  'action.create':  { en: 'Create',  ar: 'إنشاء' },
  'action.close':   { en: 'Close',   ar: 'إغلاق' },
  'action.open':    { en: 'Open',    ar: 'فتح' },
  'action.view':    { en: 'View',    ar: 'عرض' },
  // Status
  'status.active':    { en: 'Active',    ar: 'نشط' },
  'status.inactive':  { en: 'Inactive',  ar: 'غير نشط' },
  'status.pending':   { en: 'Pending',   ar: 'معلق' },
  'status.approved':  { en: 'Approved',  ar: 'معتمد' },
  'status.rejected':  { en: 'Rejected',  ar: 'مرفوض' },
  'status.completed': { en: 'Completed', ar: 'مكتمل' },
  'status.cancelled': { en: 'Cancelled', ar: 'ملغى' },
  'status.draft':     { en: 'Draft',     ar: 'مسودة' },
  'status.signed':    { en: 'Signed',    ar: 'موقع' },
  'status.paid':      { en: 'Paid',      ar: 'مدفوع' },
  'status.overdue':   { en: 'Overdue',   ar: 'متأخر' },
  'status.held':      { en: 'Held',      ar: 'محتجز' },
  // Common labels
  'label.name':      { en: 'Name',      ar: 'الاسم' },
  'label.phone':     { en: 'Phone',     ar: 'الهاتف' },
  'label.email':     { en: 'Email',     ar: 'البريد الإلكتروني' },
  'label.date':      { en: 'Date',      ar: 'التاريخ' },
  'label.amount':    { en: 'Amount',    ar: 'المبلغ' },
  'label.notes':     { en: 'Notes',     ar: 'ملاحظات' },
  'label.status':    { en: 'Status',    ar: 'الحالة' },
  'label.branch':    { en: 'Branch',    ar: 'الفرع' },
  'label.vehicle':   { en: 'Vehicle',   ar: 'المركبة' },
  'label.customer':  { en: 'Customer',  ar: 'العميل' },
  'label.contract':  { en: 'Contract',  ar: 'العقد' },
  'label.reference': { en: 'Reference', ar: 'المرجع' },
  'label.total':     { en: 'Total',     ar: 'الإجمالي' },
  'label.loading':   { en: 'Loading…',  ar: '...جار التحميل' },
  // UAE specific
  'uae.emirate':    { en: 'Emirate',    ar: 'الإمارة' },
  'uae.trn':        { en: 'TRN',        ar: 'رقم التسجيل الضريبي' },
  'uae.vat':        { en: 'VAT (5%)',   ar: 'ضريبة القيمة المضافة (5%)' },
  'uae.aed':        { en: 'AED',        ar: 'درهم' },
  'uae.emirates_id':{ en: 'Emirates ID',ar: 'الهوية الإماراتية' },
  // Platform
  'platform.title':  { en: 'Smart Mobility Platform',      ar: 'منصة التنقل الذكي' },
  'platform.tagline':{ en: 'UAE Smart Transport Management', ar: 'إدارة النقل الذكي في الإمارات' },
  'platform.home':   { en: 'Fleet360 Home',          ar: 'الرئيسية' },
  // Modules
  'module.finance':      { en: 'Finance ERP',          ar: 'المالية' },
  'module.leasing':      { en: 'Vehicle Leasing',      ar: 'تأجير المركبات' },
  'module.rental':       { en: 'Rent-A-Car',           ar: 'تأجير السيارات' },
  'module.maintenance':  { en: 'Vehicle Maintenance',  ar: 'صيانة المركبات' },
  'module.fleet':        { en: 'Fleet Management',     ar: 'إدارة الأسطول' },
  'module.logistics':    { en: 'Logistics',            ar: 'اللوجستيات' },
  'module.driver':       { en: 'Driver Management',   ar: 'إدارة السائقين' },
  'module.school_bus':   { en: 'School Bus',           ar: 'حافلة مدرسية' },
  'module.incidents':    { en: 'Incidents',            ar: 'الحوادث' },
  'module.compliance':   { en: 'Compliance',           ar: 'الامتثال' },
  'module.admin':        { en: 'Admin',                ar: 'الإدارة' },
  'module.reports':      { en: 'Reports',              ar: 'التقارير' },
  'module.approvals':    { en: 'Approvals',            ar: 'الموافقات' },
  'module.bus_ops':      { en: 'Staff Transport',      ar: 'نقل الموظفين' },
  'module.sustainability':{ en: 'Sustainability & ESG', ar: 'الاستدامة والحوكمة' },
};

/* ── Arabic translations for every nav label (value-keyed) ──────────────── */
// Used by tLabel() so layouts translate labels without restructuring NAV_GROUPS
export const arabicLabels: Record<string, string> = {
  // ── Group headers ─────────────────────────────────────────
  'Overview':               'نظرة عامة',
  'Sales Pipeline':         'خط المبيعات',
  'Sales Lifecycle':        'دورة حياة المبيعات',
  'Reservations':           'الحجوزات',
  'Rental Operations':      'عمليات التأجير',
  'Billing':                'الفواتير',
  'Billing & Finance':      'الفواتير والمالية',
  'Operational Billing':    'الفواتير التشغيلية',
  'Customer':               'العميل',
  'Compliance & Ops':       'الامتثال والعمليات',
  'Compliance & Analytics': 'الامتثال والتحليلات',
  'Fleet & Compliance':     'الأسطول والامتثال',
  'Management':             'الإدارة',
  'Operations':             'العمليات',
  'Work Management':        'إدارة العمل',
  'Garage':                 'المستودع',
  'Alerts & Monitoring':    'التنبيهات والمراقبة',
  'Data Masters':           'بيانات المرجع',
  'Administration':         'الإدارة العامة',
  'Receivables':            'المستحقات',
  'UAE Compliance':         'الامتثال الإماراتي',
  'Multi-Branch':           'متعدد الفروع',
  'Accounting':             'المحاسبة',
  // ── Nav item labels — Finance ─────────────────────────────
  'Dashboard':              'لوحة التحكم',
  'Analytics & BI':         'التحليلات والذكاء الاصطناعي',
  'CRM Pipeline':           'خط إدارة العملاء',
  'Invoices':               'الفواتير',
  'Recurring Invoices':     'الفواتير المتكررة',
  'Payments':               'المدفوعات',
  'Credit Notes':           'إشعارات الخصم',
  'AR Aging Report':        'تقرير استحقاق الذمم',
  'Collections & Dunning':  'التحصيل والمطالبات',
  'Payment Reminders':      'تذكيرات الدفع',
  'Security Deposits':      'الودائع الأمنية',
  'Expense Management':     'إدارة المصروفات',
  'Bank Reconciliation':    'تسوية البنك',
  'Budget vs Actual':       'الميزانية مقابل الفعلي',
  'PDC Register':           'سجل الشيكات المؤجلة',
  'Tax Engine':             'محرك الضرائب',
  'VAT Returns':            'إقرارات ضريبة القيمة المضافة',
  'VAT by Branch':          'ضريبة القيمة المضافة حسب الفرع',
  'VAT Consolidation':      'توحيد ضريبة القيمة المضافة',
  'Branch P&L':             'أرباح وخسائر الفرع',
  'Chart of Accounts':      'دليل الحسابات',
  'Journal Entries':        'قيود اليومية',
  'General Ledger':         'دفتر الأستاذ العام',
  'Fixed Assets':           'الأصول الثابتة',
  'Management Accounts':    'حسابات الإدارة',
  'Balance Sheet':          'الميزانية العمومية',
  'Corporate Tax (UAE)':    'ضريبة الشركات (الإمارات)',
  'Revenue Analysis':       'تحليل الإيرادات',
  'Budget Approvals':       'موافقات الميزانية',
  'Period Locking':         'قفل الفترة',
  'Audit Log':              'سجل المراجعة',
  // ── Nav item labels — Leasing ─────────────────────────────
  'Inquiries':              'الاستفسارات',
  'Quotations':             'عروض الأسعار',
  'Agreements':             'العقود',
  'Renewals':               'التجديدات',
  'Early Termination':      'الإنهاء المبكر',
  'Pre-Billing':            'الفوترة المسبقة',
  'Receipts':               'الإيصالات',
  'Receivables (AR)':       'الذمم المدينة',
  'Direct Debits':          'الخصم المباشر',
  'Traffic Fines':          'المخالفات المرورية',
  'Fuel Management':        'إدارة الوقود',
  'Mileage & Overage':      'الكيلومترات والزيادة',
  'Insurance':              'التأمين',
  'Documents':              'الوثائق',
  'Amendments':             'التعديلات',
  'Handover & Return':      'التسليم والإرجاع',
  'Vehicle Exchange':       'استبدال المركبة',
  'Vehicle Transfers':      'نقل المركبات',
  'Vehicle Returns':        'إرجاع المركبات',
  'Lessees':                'المستأجرون',
  'Credit Assessment':      'تقييم الائتمان',
  'Workflow & Approvals':   'سير العمل والموافقات',
  'Expiry Alerts':          'تنبيهات انتهاء الصلاحية',
  'Branches':               'الفروع',
  'Branch Management':      'إدارة الفروع',
  'Staff Management':       'إدارة الموظفين',
  // ── Nav item labels — RAC ────────────────────────────────
  'Bookings':               'الحجوزات',
  'Vehicle Availability':   'توفر المركبات',
  'Rental Agreements':      'اتفاقيات الإيجار',
  'Damage Claims':          'مطالبات الأضرار',
  'Rate Engine':            'محرك الأسعار',
  'Pricing':                'التسعير',
  'Customers':              'العملاء',
  'Document Vault':         'خزنة الوثائق',
  // ── Nav item labels — Maintenance ───────────────────────
  'Service Requests':       'طلبات الخدمة',
  'Predictive Maintenance': 'الصيانة التنبؤية',
  'Requests List':          'قائمة الطلبات',
  'Maintenance History':    'تاريخ الصيانة',
  'Approvals':              'الموافقات',
  'Analytics':              'التحليلات',
  'Garage Management':      'إدارة المستودع',
  'Submit Quote':           'تقديم عرض',
  'Work Orders':            'أوامر العمل',
  'Alert Configuration':    'إعداد التنبيهات',
  'Action Centre':          'مركز الإجراءات',
  'Garages':                'المستودعات',
  'Attachment Types':       'أنواع المرفقات',
  'Integrations':           'التكاملات',
  'Email / SMS Alerts':     'تنبيهات البريد / الرسائل',
  'Notification Rules':     'قواعد الإشعارات',
  // ── Module badge descriptions ─────────────────────────────
  'Contracts · Billing · Fleet · CRM':          'العقود · الفواتير · الأسطول · إدارة العملاء',
  'Inquiries · Quotes · Handover · Compliance': 'الاستفسارات · العروض · التسليم · الامتثال',
  'Predictive · Garage · Alerts · Analytics':   'التنبؤي · المستودع · التنبيهات · التحليلات',
  'Balance Sheet · CT · Budgets · Periods · Audit': 'الميزانية · ضريبة الشركات · الميزانيات · الفترات · المراجعة',
  // ── Nav item labels — Fleet ──────────────────────────────────
  'Masters':                  'البيانات الرئيسية',
  'Finance & Analytics':      'المالية والتحليلات',
  'Vehicle Types':            'أنواع المركبات',
  'Vehicle Master':           'سجل المركبات',
  'Lifecycle Events':         'أحداث دورة الحياة',
  'Allocations':              'التخصيصات',
  'Transfers':                'التحويلات',
  'Fuel Logs':                'سجلات الوقود',
  'TCO Analysis':             'تحليل التكلفة الإجمالية',
  // ── Nav item labels — Driver ─────────────────────────────────
  'Driver Profiles':          'ملفات السائقين',
  'Shifts':                   'الورديات',
  'Training':                 'التدريب',
  'Performance':              'الأداء',
  // ── Nav item labels — Bus Ops / Staff Transport ──────────────
  'Dispatch Board':           'لوحة التوزيع',
  'Routes':                   'المسارات',
  'Route Optimizer':          'محسّن المسارات',
  'Schedules':                'الجداول الزمنية',
  'Passengers':               'الركاب',
  'Staff Members':            'أعضاء الفريق',
  'Incidents':                'الحوادث',
  // ── Nav item labels — Compliance ─────────────────────────────
  'Salik':                    'سالك',
  'Permits':                  'التصاريح',
  // ── Nav item labels — Admin ──────────────────────────────────
  'Tenants':                  'المستأجرون',
  'Branches & Regions':       'الفروع والمناطق',
  'Billing & Subscriptions':  'الفواتير والاشتراكات',
  'Roles & Permissions':      'الأدوار والصلاحيات',
  'Users':                    'المستخدمون',
  'Workflow Management':      'إدارة سير العمل',
  'Platform Info':            'معلومات المنصة',
  'Notifications':            'الإشعارات',
  'Integrations & ERP':       'التكاملات ونظام ERP',
  'E-Signing Console':        'وحدة التوقيع الإلكتروني',
  'WhatsApp Support':         'دعم واتساب',
  'Platform Settings':        'إعدادات المنصة',
  // ── Nav item labels — Reports ────────────────────────────────
  'Fleet Utilization':        'استخدام الأسطول',
  'Maintenance Cost':         'تكلفة الصيانة',
  'Driver Performance':       'أداء السائق',
  'Scheduled Reports':        'التقارير المجدولة',
  // ── Nav item labels — School Bus (emoji-prefixed labels) ──────
  '🏫 Dashboard':             '🏫 لوحة التحكم',
  '🗺️ Routes':                '🗺️ المسارات',
  '✨ Route Optimizer':        '✨ محسّن المسارات',
  '👧 Students':              '👧 الطلاب',
  '📋 Attendance':            '📋 الحضور',
  '📅 Schedules':             '📅 الجداول الزمنية',
  '🚨 Incidents':             '🚨 الحوادث',
  // ── Nav item labels — Incidents (emoji-prefixed labels) ───────
  '🚨 Dashboard':             '🚨 لوحة التحكم',
  '🔴 Active Incidents':      '🔴 الحوادث النشطة',
  '🚑 Ambulance Fleet':       '🚑 أسطول الإسعاف',
  '📋 Incident Reports':      '📋 تقارير الحوادث',
  // ── Nav item labels — Logistics (emoji-prefixed labels) ──────
  '📊 Dashboard':             '📊 لوحة التحكم',
  '🚦 Dispatch Board':        '🚦 لوحة التوزيع',
  '🗺️ Route Optimizer':       '🗺️ محسّن المسارات',
  '📋 All Trips':             '📋 جميع الرحلات',
  '🚛 Vehicles':              '🚛 المركبات',
  '👤 Drivers':               '👤 السائقون',
  '📍 Live Tracking':         '📍 التتبع المباشر',
  '💰 Freight Quotes':        '💰 عروض الشحن',
  '📈 Analytics':             '📈 التحليلات',
  // ── Nav item labels — Sustainability ─────────────────────────
  'ESG Dashboard':            'لوحة حوكمة ESG',
  'Emission Reports':         'تقارير الانبعاثات',
  'Fleet Carbon':             'كربون الأسطول',
  'Modal Shift':              'التحول الوسيط',
  'Paperless Ops':            'عمليات بلا ورق',
  'Certifications':           'الشهادات',
  'Methodology Settings':     'إعدادات المنهجية',
  // ── Nav item labels — AI & Transport Services ────────────────
  'AI Agents':                'وكلاء الذكاء الاصطناعي',
  'AI Agent Ecosystem':       'منظومة وكلاء الذكاء الاصطناعي',
  'Operations Assistant':     'المساعد التشغيلي الذكي',
  // ── Nav Categories & Global Layout ────────────────────────
  'AI & Intelligence':      'الذكاء الاصطناعي والتحليلات',
  'Transport Services':     'خدمات النقل',
  'Live Operations':        'العمليات المباشرة',
  'Fleet & Assets':         'الأسطول والأصول',
  'Governance & ESG':       'الحوكمة والاستدامة',
  'Enterprise & Admin':     'المؤسسة والإدارة',
  'Menu Settings':          'إعدادات القائمة',
  'Hidden Modules':         'الوحدات المخفية',
  'Hide from menu':         'إخفاء من القائمة',
  'Pin sidebar (keep expanded)': 'تثبيت الشريط الجانبي',
  'Unpin sidebar':          'إلغاء تثبيت الشريط',
  'Expand sidebar':         'توسيع الشريط الجانبي',
  'Collapse sidebar':       'طي الشريط الجانبي',
  'Search...':              'بحث...',
  'Search':                 'بحث',
  'Not signed in':          'غير مسجل الدخول',
  'Home':                   'الرئيسية',
  'FLEET360':               'فليت 360',
  'Mobility platform':      'منصة التنقل الذكي',
  'Platform Admin':         'مسؤول المنصة',
  'Super Administrator':    'المشرف العام',
  // ── Module & Sub-page Labels ──────────────────────────────
  'AI agents':              'وكلاء الذكاء الاصطناعي',
  'AI platform':            'منصة الذكاء الاصطناعي',
  'AI Platform':            'منصة الذكاء الاصطناعي',
  'Predictive maintenance': 'الصيانة التنبؤية',
  'Service tickets':        'تذاكر الخدمة',
  'Staff transport':        'نقل الموظفين',
  'Staff Transportation':   'نقل الموظفين',
  'School bus':             'الحافلات المدرسية',
  'Logistics':              'اللوجستيات',
  'Vehicle leasing':        'تأجير المركبات',
  'Rent-a-car':             'تأجير السيارات',
  'Vehicle maintenance':    'صيانة المركبات',
  'Fleet management':       'إدارة الأسطول',
  'Finance ERP':            'المالية والمحاسبة',
  'Sustainability & ESG':   'الاستدامة والحوكمة',
  // ── Bus Ops / Staff Transport Pages & Groups ──────────────
  'Planning':               'التخطيط',
  'Tracking':               'التتبع',
  'Workforce':              'القوى العاملة',
  'Requests':               'الطلبات',
  'Analytics':              'التحليلات',
  'Routes':                 'المسارات',
  'Route Optimization':     'تحسين المسارات',
  'Route planner':          'مخطط المسارات',
  'Schedules':              'الجداول الزمنية',
  'Schedule Templates':     'قوالب الجداول',
  'Planning Engine':        'محرك التخطيط',
  'Route Consolidation':    'دمج المسارات',
  'Transport Calendars':    'تقاويم النقل',
  'Trip Monitor':           'مراقب الرحلات',
  'Outsource Management':   'إدارة الإسناد الخارجي',
  'SLA Monitor & Alerts':   'مراقبة اتفاقيات الخدمة',
  'Optimisation Status':    'حالة التحسين',
  'Demand forecast':        'التنبؤ بالطلب',
  'Demand Forecasting':     'التنبؤ بالطلب',
  'Live Fleet Map':         'خريطة الأسطول المباشرة',
  'Geofences':              'السياج الجغرافي',
  'Gateways':               'البوابات',
  'Passengers':             'الركاب',
  'Employees':              'الموظفون',
  'Drivers Performance':    'أداء السائقين',
  'Driver Fatigue & Rest':  'إجهاد وراحة السائقين',
  'Ad-hoc & Overtime':      'الطلبات الخاصة والعمل الإضافي',
  'Transport requests':     'طلبات النقل',
  'Incidents':              'الحوادث',
  'Cost Allocation':        'توزيع التكاليف',
  'Cost Allocation & Recharge': 'توزيع التكاليف وإعادة الفوترة',
  'ESG Carbon Footprint':   'البصمة الكربونية ESG',
  // ── KPI & Dashboard Phrases ───────────────────────────────
  'Active Routes':          'المسارات النشطة',
  "Today's Trips":          'رحلات اليوم',
  'In Progress':            'قيد التنفيذ',
  'Staff Registered':       'الموظفون المسجلون',
  'Open Incidents':         'الحوادث المفتوحة',
  'Pending Requests':       'الطلبات المعلقة',
  'Quick Actions':          'إجراءات سريعة',
  'Planning Constraints (PCE)': 'قيود التخطيط (PCE)',
  'Vehicle/Resource Optimization': 'تحسين المركبات والموارد',
  'Shift SLA Monitor':      'مراقبة اتفاقية مستوى الخدمة',
  'Driver Shifts':          'ورديات السائقين',
  'Vehicle Doc Expiry':     'صلاحية وثائق المركبة',
  'Ad-Hoc / Overtime Dispatch': 'توزيع المهام الإضافية',
  'Power BI Connector':     'رابط Power BI',
  'Multilayer GIS':         'نظم المعلومات الجغرافية',
  'Rider App (PWA)':        'تطبيق الراكب (PWA)',
  'Add Route':              'إضافة مسار',
  'New Trip':               'رحلة جديدة',
  'Register Staff':         'تسجيل موظف',
  'Log Incident':           'تسجيل حادث',
  'Manage Passengers':      'إدارة الركاب',
  'View all':               'عرض الكل',
  'No trips scheduled for today.': 'لا توجد رحلات مجدولة لليوم.',
  'No trips scheduled for today. Create one.': 'لا توجد رحلات مجدولة لليوم. إنشاء رحلة.',
  'Create one.':            'إنشاء رحلة.',
  'No open incidents':      'لا توجد حوادث مفتوحة',
  'Loading dashboard...':   'جارٍ تحميل لوحة التحكم...',
  'Real-time overview of routes, trips, passengers, and incidents.': 'نظرة عامة فورية على المسارات والرحلات والركاب والحوادث.',
  'Real-time overview of routes, trips, passengers, and incidents': 'نظرة عامة فورية على المسارات والرحلات والركاب والحوادث',
  'Author PCE rules first, then analyse and apply route consolidations. Constraints gate every apply.': 'قم بإعداد قواعد محرك القيود أولاً، ثم حلل وطبق دمج المسارات.',
  'BLOCK / WARN / PENALTY rules for plans & merges': 'قواعد المنع / التحذير / الجزاءات للخطط والدمج',
  'Analyse pairs, apply merges, history & revert': 'تحليل الأزواج وتطبيق الدمج والسجل والتراجع',
  'Runcutting / blocking / roster, plus CBA and headway rules': 'تقسيم الجولات والجدولة والمناوبات وقواعد التقاطر',
  'Sequential vehicle reuse opportunities — advisory only': 'فرص إعادة استخدام المركبات المتتالية — استشارية فقط',
  // ── Fleet & Maintenance Dashboard Phrases ─────────────────
  'Fleet Dashboard':        'لوحة تحكم الأسطول',
  'Overview of your fleet operations': 'نظرة عامة على عمليات الأسطول',
  'Total fleet size':       'إجمالي حجم الأسطول',
  'Active vehicles':        'المركبات النشطة',
  'In maintenance':         'قيد الصيانة',
  'Expiring docs (30d)':    'وثائق تنتهي قريباً (30 يوم)',
  'Fleet Health Summary':   'ملخص صحة الأسطول',
  'Vehicle Availability':   'توفر المركبات',
  'Maintenance Status':     'حالة الصيانة',
  'Compliance Status':      'حالة الامتثال',
  'Risk Heat':              'مؤشر المخاطر',
  'Top 5 highest-risk vehicles — maintenance score 0–100': 'أعلى 5 مركبات خطورة — مؤشر الصيانة 0–100',
  'No vehicle risk data available': 'لا تتوفر بيانات مخاطر للمركبات',
  'Document Expiry Alert':  'تنبيه انتهاء صلاحية الوثائق',
  'Top 5 upcoming expirations in the next 30 days': 'أهم 5 انتهاءات خلال الـ 30 يوماً القادمة',
  'No expiring documents in the next 30 days': 'لا توجد وثائق منتهية الصلاحية خلال 30 يوماً',
  'Vehicle':                'المركبة',
  'days':                   'يوم',
  'Days':                   'أيام',
  'License Plate':          'لوحة الترخيص',
  'Document Type':          'نوع الوثيقة',
  'Expiry Date':            'تاريخ الانتهاء',
  'Days Remaining':         'الأيام المتبقية',
  'Control Panel':          'لوحة التحكم',
  'Vehicle Register':       'سجل المركبات',
  'Artificial Intelligence Platform': 'منصة الذكاء الاصطناعي',
  'Fleet Management':       'إدارة الأسطول',
  'Discussion...':          'المحادثة...',
  'Discussion':             'المحادثة',
  'Employee Transportation': 'نقل الموظفين',
  'School Buses':           'الحافلات المدرسية',
  'Direct Operations':      'العمليات المباشرة',
  'Governance & Sustainability': 'الحوكمة والاستدامة',
  'Enterprise & Administration': 'المؤسسة والإدارة',
  'Car Rental':             'تأجير السيارات',
  'Leasing':                'تأجير المركبات',
  'Leasing Dashboard':      'لوحة تحكم تأجير المركبات',
  'Vehicle leasing contracts, renewals, compliance, and operational billing readiness.': 'عقود تأجير المركبات والتجديدات والامتثال والجاهزية التشغيلية للفوترة.',
  'Vehicle leasing contracts, renewals, compliance, and operational billing readiness': 'عقود تأجير المركبات والتجديدات والامتثال والجاهزية التشغيلية للفوترة',
  'Focused Leasing operations after finance and remarketing cleanup.': 'عمليات التأجير المباشرة بعد المعالجات المالية والتسويقية.',
  'Focused Leasing operations after finance and remarketing cleanup': 'عمليات التأجير المباشرة بعد المعالجات المالية والتسويقية',
  'Active contracts':       'العقود النشطة',
  'Monthly revenue':        'الإيراد الشهري',
  'Portfolio value':        'قيمة المحفظة',
  'Collection rate':        'معدل التحصيل',
  'total contracts':        'إجمالي العقود',
  'active lease run-rate':  'معدل تشغيل الإيجار النشط',
  'contracted value':       'القيمة التعاقدية',
  'finance-owned collections': 'تحصيلات إدارة المالية',
  'Overdue amount':         'المبالغ المتأخرة',
  'Unbilled charges':       'الرسوم غير المفوترة',
  'Expiring policies':      'الوثائق المنتهية',
  'Needs attention':        'تتطلب الاهتمام',
  'Ready for review':       'جاهزة للمراجعة',
  'Clear':                  'سليم',
  'Next 30 days':           'خلال 30 يوماً',
  'Inquiries':              'الاستفسارات',
  'Capture leasing demand': 'تسجيل طلبات التأجير',
  'Quotations':             'عروض الأسعار',
  'Build customer offers':  'إنشاء عروض العملاء',
  'Lease Agreements':       'عقود الإيجار',
  'Lease agreements':       'عقود الإيجار',
  'Manage active agreements': 'إدارة العقود النشطة',
  'Mileage':                'الكيلومترات',
  'Readings and overage':   'القراءات والزيادة',
  'Renewals':               'التجديدات',
  'Manage renewal pipeline': 'إدارة مسار التجديد',
  'Early Terminations':     'الإنهاء المبكر للعقد',
  'Early terminations':     'الإنهاء المبكر للعقد',
  'Early termination':      'الإنهاء المبكر',
  'Close contracts cleanly': 'إغلاق العقود وتسويتها',
  'Credit Assessments':     'التقييم الائتماني',
  'Credit assessments':     'التقييم الائتماني',
  'Risk and approval checks': 'فحوصات المخاطر والموافقات',
  'Portfolio insights':     'رؤى وتحليلات المحفظة',
  'Fleet Operations':       'عمليات الأسطول',
  'Fuel, fines, insurance, and documents': 'الوقود والمخالفات والتأمين والوثائق',
  // ── Sidebar Groups & Nav Items ─────────────────────────────
  'Sales':                  'المبيعات',
  'Contracts':              'العقود',
  'Fleet & drivers':        'الأسطول والسائقين',
  'Billing & records':      'الفواتير والسجلات',
  'Master data':            'البيانات الرئيسية',
  'Monitoring':             'المراقبة',
  'Sourcing':               'التوريد',
  'Settlement':             'التسوية',
  'Network':                'الشبكة',
  'Lead channels':          'قنوات استقطاب العملاء',
  'CRM & leads':            'إدارة علاقات العملاء والفرص',
  'Transfers':              'نقل المركبات',
  'Vehicle exchanges':      'تبديل المركبات',
  'Handover':               'التسليم والاستلام',
  'Field operations':       'العمليات الميدانية',
  'Pre-billing':            'الفوترة المسبقة',
  'Branch staff':           'موظفو الفروع',
  'Bulk import':            'استيراد مجمّع',
  'Alerts':                 'التنبيهات',
  'Students':               'الطلاب',
  'Attendance':             'الحضور والغياب',
  'Stops':                  'المحطات',
  'Attendants':             'المشرفون',
  'Driver scores':          'تقييم السائقين',
  'Fees':                   'الرسوم',
  'Intelligence':           'الذكاء والتحليل',
  'Marketplace Feed':       'سوق الشحن المباشر',
  'Jobs & Requests':        'المهام والطلبات',
  'Performance Scorecard':  'بطاقة تقييم الأداء',
  'Settlement Statements':  'كشوفات التسوية',
  'Fleet Register':         'سجل الأسطول',
  'Driver Roster':          'جدول مناوبات السائقين',
  'Compliance Vault':       'خزنة الامتثال',
  'Company Profile':        'الملف التعريفي للشركة',
  'Light':                  'نهاري',
  'Dark':                   'ليلي',
  'Sign in':                'تسجيل الدخول',

  // ── Category Labels & ShortLabels ──────────────────────────
  'Services':               'الخدمات',
  'Assets':                 'الأصول',
  'Governance':             'الحوكمة',
  'ENTERPRISE':             'المؤسسة',
  'Enterprise':             'المؤسسة',
  'Operations':             'العمليات',
  'branches':               'فروع',
  'branch':                 'فرع',
  'invoices':               'فواتير',
  'vehicles':               'مركبات',
  'No modules matched':     'لم تتطابق أي وحدات مع',
  'Open Universal Command Palette': 'فتح لوحة الأوامر الشاملة',
  'Assets & People':        'الأصول والكوادر',
  'Core Fleet Operations':  'عمليات الأسطول الأساسية',
  'Safety & Governance':    'السلامة والحوكمة',
  'Transport & Services':   'النقل والخدمات',
  'AUTONOMOUS COPILOTS':    'المساعدون الذاتيون',
  'LINES OF BUSINESS':      'قطاعات الأعمال',
  'LIVE RADAR & DISPATCH':  'الرادار والترحيل المباشر',
  'FLEET & WORKFORCE':      'الأسطول والقوى العاملة',
  'COMPLIANCE & ESG':       'الامتثال والاستدامة',
  'FINANCE & BILLING':      'المالية والفوترة',
  'All Modules':            'جميع الوحدات',
  'Module':                 'وحدة',
  'Modules':                'وحدات',
  'Omni Search':            'البحث الشامل',
  'Approvals':              'الموافقات',
  'Reset Filters':          'إعادة تعيين التصفية',
  'No modules found':       'لم يتم العثور على وحدات',
  'Search modules, features, tariffs, permits, telematics...': 'ابحث في الوحدات والميزات والتعريفات والتصاريح والتتبع...',
  'Autonomous Transport & Fleet Operations': 'عمليات النقل والأسطول الذاتية',
  'Fleet360 Platform Command': 'مركز قيادة منصة فليت 360',
  'Multi-modal transport operations, predictive maintenance, staff dispatch, and ESG fleet intelligence in one unified system.': 'عمليات النقل متعددة الوسائط والصيانة التنبؤية وترحيل الموظفين وذكاء أسطول الاستدامة في نظام موحد.',

  // ── Platform Flagship & Module Cards ───────────────────────
  'AI Agent Ecosystem & Copilot': 'منظومة وكلاء الذكاء الاصطناعي والمساعد الآلي',
  '10 autonomous AI copilots — predictive maintenance, smart dispatch optimizer, accident triage, WhatsApp RAC booking assistant, and compliance ratchets.': '10 مساعدين أذكياء ذاتيين — صيانة تنبؤية، تحسين الترحيل الذكي، تصنيف الحوادث، حجز واتساب والامتثال.',
  '10 AI Agents':           '10 وكلاء أذكياء',
  'Predictive Triage':      'التصنيف التنبؤي',
  'Smart Dispatch':         'الترحيل الذكي',
  'WhatsApp AI':            'واتساب الذكي',
  'Autonomous Agents':      'وكلاء ذاتيون',
  '10 Online':              '10 متصل',
  'AI Accuracy':            'دقة الذكاء الاصطناعي',
  'Triage Speed':           'سرعة التصنيف',
  'Cost Avoidance':         'التكاليف المتفاداة',
  'Agent Command':          'قيادة الوكلاء',
  'Threshold Tuning':       'ضبط المعايير والحدود',
  'AI Platform & Governance': 'منصة الذكاء الاصطناعي والحوكمة',
  'Autonomous policy guardrails (L0–L4), financial token spend budgets, multi-provider AI gateway, and ground-truth model benchmarks.': 'ضوابط السياسات الذاتية (L0-L4)، ميزانيات استهلاك الرموز، بوابة المزودين المتعددين ومعايير النماذج.',
  'ROI Tracking':           'تتبع العائد على الاستثمار',
  'AI Gateway':             'بوابة الذكاء الاصطناعي',
  'Benchmarks':             'المعايير المرجعية',
  'Net ROI':                'صافي العائد على الاستثمار',
  'Autonomy Level':         'مستوى الاستقلالية',
  'L2 Guarded':             'L2 محمي',
  'Model Quality':          'جودة النموذج',
  'ROI Dashboard':          'لوحة عائد الاستثمار',
  'Set Policy':             'تعيين السياسة',
  'Staff Transportation (STS)': 'نقل الموظفين (STS)',
  'Fixed corporate bus route schedules, PCE constraint optimization, passenger manifests, shift roster synchronization, and live boarding tracking.': 'جداول الحافلات المؤسسية الثابتة، تحسين قيود محرك PCE، بيانات الركاب ومزامنة الورديات والتتبع المباشر.',
  'Staff Shuttles':         'حافلات نقل الموظفين',
  'PCE Optimizer':          'محسن قيود PCE',
  'Shift Sync':             'مزامنة الورديات',
  'Passenger Manifest':     'بيان الركاب',
  'Monthly Pax':            'الركاب شهرياً',
  'Route Planner':          'مخطط المسارات',
  'School Bus Transportation': 'نقل الحافلات المدرسية',
  'Student safety registry, RFID badge attendance tracking, guardian WhatsApp SMS alerts, and DOT safety compliance.': 'سجل سلامة الطلاب، تتبع الحضور ببطاقات RFID، تنبيهات أولياء الأمور عبر واتساب والامتثال لسلامة النقل.',
  'Student RFID':           'بطاقات RFID للطلاب',
  'Guardian Alerts':        'تنبيهات أولياء الأمور',
  'DOT Safety':             'معايير سلامة النقل',
  'Active Students':        'الطلاب النشطون',
  'Live Buses':             'الحافلات المباشرة',
  'Logistics & Freight Ops': 'العمليات اللوجستية والشحن',
  'End-to-end heavy logistics dispatch, digital ePOD, bulk consignment merge optimizer, cold chain telematics, and route tracking.': 'إدارة الشحن الثقيل الشاملة، إثبات التسليم الرقمي ePOD، دمج الشحنات، تتبع سلسلة التبريد والمسارات.',
  'Heavy Freight':          'الشحن الثقيل',
  'Digital ePOD':           'إثبات التسليم الرقمي',
  'Cold Chain':             'سلسلة التبريد',
  'Multi-Drop':             'تعدد نقاط التوصيل',
  'In Transit':             'قيد النقل',
  'On-Time Rate':           'نسبة الالتزام بالوقت',
  'Vehicle Long-Term Leasing': 'التأجير التشغيلي طويل الأجل للمركبات',
  'Corporate long-term leases, automated monthly billing, lessee profiles, contract renewals, and return inspection scoring.': 'عقود التأجير المؤسسي طويل الأجل، الفوترة الشهرية التلقائية، تجديد العقود وفحص الاسترجاع.',
  'Corporate Leases':       'عقود إيجار الشركات',
  'Billing Schedules':      'جداول الفوترة',
  'Vehicle Returns':        'استرجاع المركبات',
  'Active Leases':          'العقود النشطة',
  'Renewals (30d)':         'التجديدات (30 يوم)',
  'Rent-A-Car (RAC) Operations': 'عمليات تأجير السيارات (RAC)',
  'Fleet RAC desk, dynamic tariffs, customer KYC, cross-border permits (Oman/KSA), damage claims, and automated traffic fine billing.': 'كاونتر التأجير اليومي، التعريفات الديناميكية، التحقق من هوية العميل KYC، تصاريح السفر ومطالبات الأضرار.',
  'Daily/Weekly RAC':       'تأجير يومي / أسبوعي',
  'KYC Verification':       'التحقق من الهوية KYC',
  'Cross-Border Permits':   'تصاريح السفر الدولية',
  'Damage Claims':          'مطالبات الأضرار',
  'RAC Fleet Size':         'حجم أسطول التأجير اليومي',
  'Active Bookings':        'الحجوزات النشطة',
  'Fleet Utilization':      'نسبة استغلال الأسطول',
  'Avg Daily Rate':         'متوسط السعر اليومي',
  '+ New Booking':          '+ حجز جديد',
  'Tariff Master':          'جدول التعريفات',
  'Dispatch Control Center': 'مركز التحكم والترحيل',
  'Driver Operations & HOS': 'عمليات السائقين وساعات الخدمة',
  'Driver license & visa compliance, HOS shift logs, automated driver scoring, and performance telematics.': 'امتثال الرخص والإقامات، سجلات ساعات العمل HOS، وتقييم السائقين التلقائي.',
  'Driver Scoring':         'تقييم السائقين',
  'HOS Logs':               'سجلات ساعات الخدمة HOS',
  'Document Vault':         'خزنة الوثائق',
  'Assets & Field Inventory': 'الأصول والمخزون الميداني',
  'High-Value Asset (HVA) calibration logs, BLE beacon tracking, medical supplies, and reverse logistics.': 'معايرة الأصول عالية القيمة HVA، تتبع البلوتوث BLE، الإمدادات الطبية واللوجستيات العكسية.',
  'HVA Tracking':           'تتبع الأصول الثمينة HVA',
  'BLE Beacons':            'منارات البلوتوث BLE',
  'Inventory':              'المخزون',
  'RTA Compliance & Salik': 'امتثال هيئة الطرق والمواصلات وسالك',
  'RTA commercial road permits, commercial vehicle inspections, insurance policies, and electronic document validation.': 'تصاريح النقل التجاري RTA، الفحص الفني الدوري، وثائق التأمين وتدقيق المستندات إلكترونياً.',
  'RTA Road Permits':       'تصاريح الطرق RTA',
  'Insurance Policies':     'وثائق التأمين',
  'Salik Tag Sync':         'مزامنة بطاقات سالك',
  'ESG & Carbon Intelligence': 'الاستدامة والذكاء الكربوني ESG',
  'GHG Protocol / ISO 14064 certified CO2 emission tracking, EV fleet transition roadmap, and UAE Net Zero 2050 metrics.': 'تتبع انبعاثات الكربون المعتمد، خارطة تحول المركبات الكهربائية ومؤشرات الحياد المناخي 2050.',
  'Scope 1/2/3':            'النطاق 1/2/3',
  'EV Transition':          'التحول للمركبات الكهربائية',
  'Cross-Module BI Reports': 'تقارير ذكاء الأعمال الموحدة',
  'Fleet utilization heatmap, revenue analytics, maintenance cost breakdown, and automated PDF / Excel exports.': 'خريطة استخدام الأسطول، تحليلات الإيرادات، تفصيل تكاليف الصيانة والتصدير التلقائي.',
  'Fleet Analytics':        'تحليلات الأسطول',
  'Revenue BI':             'ذكاء الإيرادات',
  'Scheduled Exports':      'التصدير المجدول',
  'Customer Master & CRM':  'سجل العملاء وإدارة العلاقات CRM',
  '3-tier hierarchy (Region, Department, Unit), credit limits, contract master, and communication history.': 'هيكل ثلاثي المستويات (المنطقة، القسم، الوحدة)، الحدود الائتمانية وسجل العقود.',
  '3-Tier Hierarchy':       'هيكل ثلاثي المستويات',
  'Credit Master':          'سجل الائتمان',
  'Finance & VAT Billing':  'المالية وفوترة ضريبة القيمة المضافة',
  'Automated FTA-compliant Tax Invoices, Salik toll batch reconciliation, payment receipts, and revenue reports.': 'فواتير ضريبية معتمدة من الهيئة الاتحادية للضرائب، تسوية رسوم سالك وسندات القبض.',
  'FTA Tax Invoices':       'فواتير ضريبية معتمدة FTA',
  'Salik Tolls':            'رسوم سالك المرورية',
  '5% VAT Engine':          'محرك ضريبة 5%',

  // ── All Sub-Pages & Navigation Modules ─────────────────────
  // ── RAC / Rental Dashboard ────────────────────────────────
  'RAC Dashboard':          'لوحة تحكم تأجير السيارات (RAC)',
  'Rent-a-Car — Real-time overview': 'تأجير السيارات — نظرة عامة فورية',
  'All time':               'طوال الوقت',
  'blacklisted':            'في القائمة السوداء',
  'total':                  'إجمالي',
  'Recent Bookings':        'أحدث الحجوزات',
  'No bookings yet.':       'لا توجد حجوزات حتى الآن.',
  'Create one.':            'إنشاء حجز.',
  'REF':                    'المرجع',
  'CUSTOMER':               'العميل',
  'CATEGORY':               'الفئة',
  'PICKUP':                 'الاستلام',
  'RETURN':                 'الإرجاع',
  'AMOUNT':                 'المبلغ',
  'STATUS':                 'الحالة',
  'PENDING':                'معلق',
  'CONFIRMED':              'مؤكد',
  'ACTIVE':                 'نشط',
  'COMPLETED':              'مكتمل',
  'CANCELLED':              'ملغى',
  'Pending':                'معلق',
  'Confirmed':              'مؤكد',
  'Active':                 'نشط',
  'Completed':              'مكتمل',
  'Cancelled':              'ملغى',
  'New Booking':            'حجز جديد',
  'Add Customer':           'إضافة عميل',
  'Check Availability':     'فحص التوفر',
  // ── Finance Dashboard & Reporting ─────────────────────────
  'Finance Hub':            'مركز المالية',
  'Cross-module financial aggregation — read-only reporting layer': 'تجميع مالي لجميع الوحدات — طبقة تقارير للقراءة فقط',
  'From':                   'من',
  'To':                     'إلى',
  'Clear':                  'مسح',
  'Refresh':                'تحديث',
  'Retry':                  'إعادة المحاولة',
  'Total Revenue':          'إجمالي الإيرادات',
  'Vehicle Costs':          'تكاليف المركبات',
  'Gross Profit':           'إجمالي الربح',
  'Cash Received':          'النقد المستلم',
  'Rental + Leasing + General': 'التأجير اليومي + التأجير طويل الأجل + عام',
  'Approved maintenance spend': 'مصروفات الصيانة المعتمدة',
  'margin':                 'هامش الربح',
  'transactions':           'معاملات',
  'txns':                   'معاملات',
  'P&L Overview':           'نظرة عامة على الأرباح والخسائر',
  'Revenue':                'الإيرادات',
  'Costs':                  'التكاليف',
  'Revenue & Cost by Module': 'الإيرادات والتكاليف حسب الوحدة',
  'Revenue & Cost by Module': 'الإيرادات والتكاليف حسب الوحدة',
  'Each module owns its own transactions — Finance aggregates read-only': 'كل وحدة تدير معاملاتها الخاصة — المالية تقوم بالتجميع للقراءة فقط',
  'Module':                 'الوحدة',
  'Type':                   'النوع',
  'Amount (AED)':           'المبلغ (درهم)',
  'Documents':              'المستندات',
  'Share of Revenue':       'الحصة من الإيرادات',
  'Vehicle Maintenance':    'صيانة المركبات',
  'Rent-A-Car (RAC)':       'تأجير السيارات (RAC)',
  'Vehicle Leasing':        'تأجير المركبات',
  'General Invoicing':      'الفوترة العامة',
  'Finance Invoices':       'فواتير المالية',
  'Received Payments':      'المدفوعات المستلمة',
  'REVENUE':                'إيراد',
  'COST':                   'تكلفة',
  'CASH':                   'نقد',
  'View →':                 'عرض ←',
  'View':                   'عرض',
  'Maintenance Costs':      'تكاليف الصيانة',
  'Rental Revenue':         'إيرادات تأجير السيارات',
  'Hub-and-Spoke Finance Architecture': 'بنية مالية مركزية وموزعة',
  'Finance Hub is a read-only aggregation layer. Each operational module (Rental, Leasing, Maintenance) independently processes its own payments without Finance team approval. This dashboard consolidates those numbers in real time. No transaction is blocked waiting for Finance — the hub reads, never writes.': 'يعمل مركز المالية كطبقة تجميعية للقراءة فقط. تعالج كل وحدة تشغيلية (التأجير اليومي، التأجير طويل الأجل، الصيانة) مدفوعاتها بشكل مستقل دون انتظار موافقة فريق المالية. تعرض هذه اللوحة الأرقام لحظياً دون تعطيل أي معاملة.',
  'Mobility — Platform':    'منصة التنقل الذكي',
  'Mobility - Platform':    'منصة التنقل الذكي',
  'Live map':               'الخريطة المباشرة',
  'Seat availability':      'توفر المقاعد',
  'Allocations':            'التخصيصات',
  'Control tower':          'برج المراقبة والتحكم',
  'Dispatch board':         'لوحة الترحيل',
  'Freight marketplace':    'سوق الشحن',
  'Carrier network':        'شبكة الناقلين',
  'Shippers':               'الشاحنون',
  'Shipping requests':      'طلبات الشحن',
  'Route optimizer':        'محسن المسارات',
  'Shipment orders':        'أوامر الشحن',
  'Vehicles':               'المركبات',
  'Drivers':                'السائقون',
  'Live tracking':          'التتبع المباشر',
  'Freight quotes':         'عروض أسعار الشحن',
  'Rate contracts':         'عقود الأسعار',
  'Settlements':            'التسويات',
  'Counter':                'كاونتر التأجير',
  'Bookings':               'الحجوزات',
  'Agreements':             'العقود والاتفاقيات',
  'Damage claims':          'مطالبات الأضرار',
  'Ancillaries':            'الخدمات الإضافية',
  'Pricing':                'التسعير',
  'Rates':                  'الأسعار والتعريفات',
  'Availability':           'التوفر والجاهزية',
  'Channels':               'قنوات التوزيع',
  'Insurance':              'التأمين',
  'Branches':               'الفروع',
  'Staff':                  'الموظفون',
  'Command':                'مركز القيادة',
  'Jobs':                   'المهام والطلبات',
  'Ambulance':              'الإسعاف الطبي',
  'Merge':                  'دمج الرحلات',
  'Fleet360 Exchange':      'منصة تبادل فليت 360',
  'Active':                 'النشطة',
  'Booking portal':         'بوابة الحجز',
  'New booking':            'حجز جديد',
  'My bookings':            'حجوزاتي',
  'Mobile apps':            'تطبيقات الجوال',
  'Booking App':            'تطبيق الحجز',
  'PWA Gallery':            'معرض تطبيقات الويب',
  'STS Driver':             'تطبيق سائق نقل الموظفين',
  'STS Passenger':          'تطبيق ركاب الموظفين',
  'RAC Counter':            'تطبيق كاونتر التأجير',
  'Leasing Field':          'تطبيق تأجير الميدان',
  'SchoolBus Parent':       'تطبيق أولياء الأمور',
  'SchoolBus Driver':       'تطبيق سائق الحافلة المدرسية',
  'Fleet':                  'الأسطول',
  'Live Telematics & IoT':  'التتبع المباشر وإنترنت الأشياء',
  'CAN-bus diagnostics':    'تشخيصات CAN-bus',
  'Vehicle master':         'البيانات الرئيسية للمركبات',
  'Vehicle types':          'أنواع المركبات',
  'Lifecycle events':       'أحداث دورة الحياة',
  'Work orders':            'أوامر العمل',
  'Hours of service':       'ساعات الخدمة والعمل',
  'Fuel logs':              'سجلات الوقود',
  'Traffic fines':          'المخالفات المرورية',
  'TCO analysis':           'تحليل التكلفة الإجمالية TCO',
  'Maintenance':            'الصيانة',
  'Requests list':          'قائمة طلبات الصيانة',
  'Maintenance history':    'سجل الصيانة',
  'PM plans':               'خطط الصيانة الوقائية',
  'Schedule':               'جدول المواعيد',
  'Garage assignments':     'إسناد الورش والكراجات',
  'Predictive alerts':      'تنبيهات الصيانة التنبؤية',
  'Warranties':             'الضمانات',
  'Breakdowns':             'الأعطال المفاجئة',
  'SLA':                    'اتفاقية مستوى الخدمة SLA',
  'Risk scores':            'مؤشرات المخاطر',
  'Profiles':               'الملفات الشخصية',
  'Shifts':                 'الورديات',
  'Training':               'التدريب والتأهيل',
  'Performance':            'الأداء',
  'Registry':               'سجل الأصول',
  'Categories':             'الفئات والتصنيفات',
  'Stock':                  'المخزون والمستودع',
  'Transactions':           'الحركات والعمليات',
  'Timeline':               'الجدول الزمني',
  'Map':                    'الخريطة',
  'HVA':                    'الأصول عالية القيمة HVA',
  'Medical':                'المعدات الطبية',
  'Personnel':              'العهد الشخصية',
  'Returns':                'المرتجعات',
  'SPM':                    'قطع الغيار والصيانة',
  'BLE tags':               'علامات البلوتوث BLE',
  'BLE zones':              'نطاقات البلوتوث BLE',
  'BLE gateways':           'بوابات البلوتوث BLE',
  'BLE detections':         'رصد البلوتوث BLE',
  'BLE alerts':             'تنبيهات البلوتوث BLE',
  'Locations':              'المواقع والمحطات',
  'Compliance':             'الامتثال والتراخيص',
  'Documents':              'المستندات والوثائق',
  'Permits':                'التصاريح والتراخيص',
  'Salik':                  'سالك',
  'Sustainability':         'الاستدامة',
  'Fleet carbon':           'انبعاثات كربون الأسطول',
  'Modal shift':            'التحول النموذجي للنقل',
  'Paperless':              'العمليات غير الورقية',
  'Certifications':         'الشهادات والاعتمادات',
  'Settings':               'الإعدادات',
  'Reports':                'التقارير',
  'Fleet utilisation':      'معدل استغلال الأسطول',
  'Revenue':                'الإيرادات',
  'Driver performance':     'أداء السائقين',
  'Scheduled reports':      'التقارير المجدولة',
  'Vendors & Partners':     'الموردون والشركاء',
  'Overview':               'نظرة عامة',
  'Transport Outsourcing':  'إسناد خدمات النقل',
  'Partner Marketplace':    'سوق الشركاء',
  'Partner Scorecards':     'بطاقات أداء الشركاء',
  'Settlements & Tax Invoices': 'التسويات والفواتير الضريبية',
  'Maintenance & Garages':  'الصيانة والورش والكراجات',
  'Garage management':      'إدارة الورش والكراجات',
  'Garage portal':          'بوابة الكراجات',
  'Customers':              'العملاء',
  'Hierarchy setup':        'هيكل تسلسل العملاء',
  'Finance':                'المالية والمحاسبة',
  'Recurring invoices':     'الفواتير الدورية',
  'Payments':               'المدفوعات والمقبوضات',
  'Credit notes':           'الإشعارات الدائنة',
  'AR aging':               'أعمار الذمم المدينة AR',
  'Collections':            'التحصيل والمتابعة',
  'Payment reminders':      'تذكيرات السداد',
  'PDC register':           'سجل الشيكات المؤجلة PDC',
  'Tax engine':             'محرك الضرائب',
  'VAT returns':            'إقرارات ضريبة القيمة المضافة',
  'VAT by branch':          'ضريبة القيمة المضافة حسب الفرع',
  'Branch P&L':             'أرباح وخسائر الفروع P&L',
  'Security deposits':      'التأمينات والودائع',
  'Expense management':     'إدارة المصروفات',
  'Bank reconciliation':    'التسوية البنكية',
  'Budget vs actual':       'الموازنة مقابل الفعلي',
  'Chart of accounts':      'دليل الحسابات',
  'Journal entries':        'قيود اليومية',
  'General ledger':         'دفتر الأستاذ العام',
  'Fixed assets':           'الأصول الثابتة',
  'Income statement':       'قائمة الدخل',
  'Revenue analysis':       'تحليل الإيرادات',
  'Balance sheet':          'الميزانية العمومية',
  'Corporate tax (UAE)':    'ضريبة الشركات (الإمارات)',
  'Budget approvals':       'اعتمادات الموازنة',
  'Period locking':         'إقفال الفترات المحاسبية',
  'Anomaly detection':      'اكتشاف العمليات غير المعتادة',
  'Admin':                  'لوحة الإدارة',
  'Users':                  'المستخدمون',
  'Roles & permissions':    'الأدوار والصلاحيات',
  'Branches & regions':     'الفروع والمناطق',
  'Billing & subscriptions':'الاشتراكات والفوترة',
  'Tenants':                'حسابات المؤسسات المستأجرة',
  'Service configuration':  'إعدادات الخدمات',
  'Audit log':              'سجل التدقيق والمراجعة',
  'Audit logs':             'سجلات التدقيق والمراجعة',
  'Platform settings':      'إعدادات المنصة',
  'Alert engine':           'محرك التنبيهات',
  'WhatsApp console':       'لوحة تحكم واتساب',
  'Dispatch monitor':       'مراقب الترحيل',
  'E-signing console':      'لوحة التوقيع الإلكتروني',
  'Shipper portal config':  'إعدادات بوابة الشاحنين',
  'Platform info':          'معلومات المنصة',
  'Workflow management':    'إدارة مسارات العمل',
  'Subscription':           'الاشتراك',
  'Brand preview':          'معاينة الهوية البصرية',

  // ── Switchers & Session UI ─────────────────────────────────
  'Select Branch':          'اختر الفرع',
  'All Branches':           'جميع الفروع',
  'Consolidated view across all regions': 'عرض مجمع لجميع المناطق',
  'License Expired':        'الرخصة منتهية',
  'Expiring Soon':          'تنتهي قريباً',
  'Branch selection filters invoices, vehicles & reports': 'تحديد الفرع يقوم بتصفية الفواتير والمركبات والتقارير',
  'Switch User':            'تبديل المستخدم',
  'Sign out / Switch Tenant':'تسجيل الخروج / تبديل المؤسسة',
  'No other users in this tenant': 'لا يوجد مستخدمون آخرون في هذه المؤسسة',
  '(you)':                  '(أنت)',
  '(inactive)':             '(غير نشط)',
  // ── Common page phrases ───────────────────────────────────
  'Loading…':               '...جار التحميل',
  'No data found':          'لا توجد بيانات',
  'Save':                   'حفظ',
  'Cancel':                 'إلغاء',
  'Delete':                 'حذف',
  'Edit':                   'تعديل',
  'Close':                  'إغلاق',
  'Approve':                'موافقة',
  'Reject':                 'رفض',
  'Submit':                 'إرسال',
  'Export XLSX':            'تصدير XLSX',
  'New':                    'جديد',
  'Create':                 'إنشاء',
  'View':                   'عرض',
  'Back':                   'رجوع',
  'Generate Now':           'إنشاء الآن',
  'Run All Now':            'تشغيل الكل الآن',
  'Add Deduction':          'إضافة خصم',
  'Process Refund':         'معالجة الاسترداد',
  'Forfeit Deposit':        'مصادرة الوديعة',

  // Authentication & Login Page
  'Signing in…':            'جارٍ تسجيل الدخول…',
  'Two-factor required':    'المصادقة الثنائية مطلوبة',
  'Welcome back — enter your credentials below.': 'مرحباً بعودتك — أدخل بيانات اعتمادك أدناه.',
  'Enter the 6-digit code from your authenticator app.': 'أدخل الرمز المكون من 6 أرقام من تطبيق المصادقة.',
  'Enter one of your recovery codes.': 'أدخل أحد رموز الاسترداد الخاصة بك.',
  'Work email':             'بريد العمل الإلكتروني',
  'Email address':          'عنوان البريد الإلكتروني',
  'Password':               'كلمة المرور',
  'Show':                   'إظهار',
  'Hide':                   'إخفاء',
  'Continue with SSO':      'المتابعة باستخدام SSO',
  'Sign in with SSO →':     'تسجيل الدخول باستخدام SSO ←',
  'Sign in with password instead': 'تسجيل الدخول بكلمة المرور بدلاً من ذلك',
  'Forgot your password?':  'هل نسيت كلمة المرور؟',
  'Recovery code':          'رمز الاسترداد',
  'Authenticator code':     'رمز المصادقة',
  'Verify and continue':    'تحقق ومتابعة',
  'Verifying…':             'جارٍ التحقق…',
  'Use authenticator instead': 'استخدام تطبيق المصادقة بدلاً من ذلك',
  'Use a recovery code':    'استخدام رمز الاسترداد',
  'New to Fleet360?':       'جديد في Fleet360؟',
  'Create your organisation': 'إنشاء مؤسستك',
  'Fleet Management Platform': 'منصة إدارة الأساطيل',
  'Multi-Tenant Platform':  'منصة متعددة المستأجرين',
};

// Normalized lowercase map for case-insensitive lookup
const lowerArabicMap: Record<string, string> = {};
for (const [k, v] of Object.entries(arabicLabels)) {
  lowerArabicMap[k.toLowerCase().trim()] = v;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: 'en',
  isRTL: false,
  setLanguage: () => {},
  t: (key) => key,
  tLabel: (english) => english,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Default to 'en' (English always unless tenant specifies Arabic)
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('xlai_language') as Language | null;
    if (saved === 'ar' || saved === 'en') {
      setLanguageState(saved);
    } else {
      setLanguageState('en');
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir  = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    localStorage.setItem('xlai_language', language);
  }, [language]);

  const setLanguage = (lang: Language) => setLanguageState(lang);

  const t = (key: string): string =>
    translations[key]?.[language] ?? translations[key]?.en ?? key;

  /** Translate by English label value — case-insensitive with punctuation trim */
  const tLabel = (english: string): string => {
    if (language !== 'ar') return english;
    if (!english || typeof english !== 'string') return english;
    const trimmed = english.trim();
    if (arabicLabels[trimmed]) return arabicLabels[trimmed];
    const lower = trimmed.toLowerCase();
    if (lowerArabicMap[lower]) return lowerArabicMap[lower];
    const stripped = lower.replace(/[:.]$/, '').trim();
    if (lowerArabicMap[stripped]) return lowerArabicMap[stripped];
    return english;
  };

  return (
    <LanguageContext.Provider value={{ language, isRTL: language === 'ar', setLanguage, t, tLabel }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
