/**
 * Translation strings used across PDF templates.
 * Keep keys flat and short. Add new modules as new top-level keys.
 */

import type { Lang } from './theme';

export const pdfStrings = {
  // Generic
  quotation: { en: 'Quotation', ar: 'عرض سعر' },
  invoice: { en: 'Tax Invoice', ar: 'فاتورة ضريبية' },
  receipt: { en: 'Receipt', ar: 'إيصال' },
  contract: { en: 'Lease Agreement', ar: 'عقد إيجار' },
  statement: { en: 'Account Statement', ar: 'كشف حساب' },

  number: { en: 'No.', ar: 'رقم' },
  date: { en: 'Date', ar: 'التاريخ' },
  validUntil: { en: 'Valid Until', ar: 'صالح حتى' },
  page: { en: 'Page', ar: 'صفحة' },
  of: { en: 'of', ar: 'من' },

  // Parties
  billTo: { en: 'Bill To', ar: 'فاتورة إلى' },
  from: { en: 'From', ar: 'من' },
  tradeLicense: { en: 'Trade License', ar: 'رخصة تجارية' },
  trn: { en: 'TRN', ar: 'الرقم الضريبي' },
  emiratesId: { en: 'Emirates ID', ar: 'الهوية الإماراتية' },
  phone: { en: 'Phone', ar: 'هاتف' },
  email: { en: 'Email', ar: 'البريد الإلكتروني' },

  // Vehicle table
  vehicle: { en: 'Vehicle', ar: 'المركبة' },
  make: { en: 'Make', ar: 'الصانع' },
  model: { en: 'Model', ar: 'الموديل' },
  year: { en: 'Year', ar: 'السنة' },
  qty: { en: 'Qty', ar: 'الكمية' },
  monthlyRate: { en: 'Monthly Rate', ar: 'الإيجار الشهري' },
  subtotal: { en: 'Subtotal', ar: 'المجموع الفرعي' },

  // Cost lines
  baseRent: { en: 'Base Rent', ar: 'الإيجار الأساسي' },
  insurance: { en: 'Insurance', ar: 'التأمين' },
  maintenance: { en: 'Maintenance', ar: 'الصيانة' },
  driver: { en: 'Driver', ar: 'السائق' },
  accessories: { en: 'Accessories', ar: 'الإكسسوارات' },
  vat: { en: 'VAT (5%)', ar: 'ضريبة القيمة المضافة (5%)' },
  grandTotal: { en: 'Grand Total', ar: 'الإجمالي الكلي' },
  total: { en: 'Total', ar: 'الإجمالي' },

  // Terms
  leaseType: { en: 'Lease Type', ar: 'نوع العقد' },
  longTerm: { en: 'Long-term', ar: 'طويل الأمد' },
  shortTerm: { en: 'Short-term', ar: 'قصير الأمد' },
  duration: { en: 'Duration', ar: 'المدة' },
  months: { en: 'months', ar: 'شهر' },
  mileageCap: { en: 'Mileage Cap (km / month)', ar: 'الحد الأقصى للكيلومترات (شهرياً)' },
  securityDeposit: { en: 'Security Deposit', ar: 'مبلغ التأمين' },
  notes: { en: 'Notes', ar: 'ملاحظات' },

  // Lessee types
  corporate: { en: 'Corporate', ar: 'شركة' },
  individual: { en: 'Individual', ar: 'فرد' },

  // Signatures
  authorizedSignature: { en: 'Authorized Signature', ar: 'التوقيع المعتمد' },
  lesseeAcknowledgment: { en: 'Lessee Acknowledgment', ar: 'إقرار المستأجر' },
  signedBy: { en: 'Signed by', ar: 'وقع بواسطة' },
  signatureDate: { en: 'Signature Date', ar: 'تاريخ التوقيع' },

  // Boilerplate
  termsHeading: { en: 'Terms & Conditions', ar: 'الشروط والأحكام' },
  quotationDisclaimer: {
    en: 'This quotation is subject to credit approval and signed agreement. Prices are inclusive of UAE VAT at the prevailing rate. Validity expires on the date shown above. All vehicles remain the property of the lessor throughout the lease term.',
    ar: 'يخضع هذا العرض للموافقة على الائتمان والتوقيع على الاتفاقية. الأسعار شاملة لضريبة القيمة المضافة في الإمارات بالنسبة المعمول بها. ينتهي صلاحية العرض في التاريخ المبين أعلاه. تظل جميع المركبات ملكاً للمؤجر طوال فترة الإيجار.',
  },
  generatedBy: { en: 'Generated by Smart Mobility Platform', ar: 'تم الإنشاء بواسطة منصة التنقل الذكي' },

  // Pre-billing
  billingPeriod: { en: 'Billing Period', ar: 'فترة الفوترة' },
  dueDate: { en: 'Due Date', ar: 'تاريخ الاستحقاق' },
  fuelCharges: { en: 'Fuel Charges', ar: 'رسوم الوقود' },
  fineCharges: { en: 'Traffic Fines', ar: 'المخالفات المرورية' },
  overageCharges: { en: 'Mileage Overage', ar: 'تجاوز الكيلومترات' },
  otherCharges: { en: 'Other Charges', ar: 'رسوم أخرى' },
  contractRef: { en: 'Contract Ref.', ar: 'مرجع العقد' },
  reviewWindowNote: {
    en: 'This is a pre-billing statement. Please review and confirm by the due date. Final invoice will follow.',
    ar: 'هذا كشف فوترة مسبق. يرجى المراجعة والتأكيد قبل تاريخ الاستحقاق. ستتبع الفاتورة النهائية.',
  },
  itemisedDetail: { en: 'Itemised Detail', ar: 'التفاصيل المفصلة' },
  description: { en: 'Description', ar: 'الوصف' },
  amount: { en: 'Amount', ar: 'المبلغ' },
} as const;

export type PdfStringKey = keyof typeof pdfStrings;

export function t(key: PdfStringKey, lang: Lang): string {
  return pdfStrings[key][lang];
}
