/**
 * Translation strings used across PDF templates.
 * Keep keys flat and short. Add new modules as new top-level keys.
 */

import type { Lang } from './theme';

export const pdfStrings = {
  // Generic
  quotation: { en: 'Quotation', ar: 'عرض سعر' },
  invoice: { en: 'Tax Invoice', ar: 'فاتورة ضريبية' },
  receipt: { en: 'Receipt', ar: 'إيصال' },
  contract: { en: 'Lease Agreement', ar: 'عقد إيجار' },
  statement: { en: 'Account Statement', ar: 'كشف حساب' },

  number: { en: 'No.', ar: 'رقم' },
  date: { en: 'Date', ar: 'التاريخ' },
  validUntil: { en: 'Valid Until', ar: 'صالح حتى' },
  page: { en: 'Page', ar: 'صفحة' },
  of: { en: 'of', ar: 'من' },

  // Parties
  billTo: { en: 'Bill To', ar: 'فاتورة إلى' },
  from: { en: 'From', ar: 'من' },
  tradeLicense: { en: 'Trade License', ar: 'رخصة تجارية' },
  trn: { en: 'TRN', ar: 'الرقم الضريبي' },
  emiratesId: { en: 'Emirates ID', ar: 'الهوية الإماراتية' },
  phone: { en: 'Phone', ar: 'هاتف' },
  email: { en: 'Email', ar: 'البريد الإلكتروني' },

  // Vehicle table
  vehicle: { en: 'Vehicle', ar: 'المركبة' },
  make: { en: 'Make', ar: 'الصانع' },
  model: { en: 'Model', ar: 'الموديل' },
  year: { en: 'Year', ar: 'السنة' },
  qty: { en: 'Qty', ar: 'الكمية' },
  monthlyRate: { en: 'Monthly Rate', ar: 'الإيجار الشهري' },
  subtotal: { en: 'Subtotal', ar: 'المجموع الفرعي' },

  // Cost lines
  baseRent: { en: 'Base Rent', ar: 'الإيجار الأساسي' },
  insurance: { en: 'Insurance', ar: 'التأمين' },
  maintenance: { en: 'Maintenance', ar: 'الصيانة' },
  driver: { en: 'Driver', ar: 'السائق' },
  accessories: { en: 'Accessories', ar: 'الإكسسوارات' },
  vat: { en: 'VAT (5%)', ar: 'ضريبة القيمة المضافة (5%)' },
  grandTotal: { en: 'Grand Total', ar: 'الإجمالي الكلي' },
  total: { en: 'Total', ar: 'الإجمالي' },

  // Terms
  leaseType: { en: 'Lease Type', ar: 'نوع العقد' },
  longTerm: { en: 'Long-term', ar: 'طويل الأمد' },
  shortTerm: { en: 'Short-term', ar: 'قصير الأمد' },
  duration: { en: 'Duration', ar: 'المدة' },
  months: { en: 'months', ar: 'شهر' },
  mileageCap: { en: 'Mileage Cap (km / month)', ar: 'الحد الأقصى للكيلومترات (شهرياً)' },
  securityDeposit: { en: 'Security Deposit', ar: 'مبلغ التأمين' },
  notes: { en: 'Notes', ar: 'ملاحظات' },

  // Lessee types
  corporate: { en: 'Corporate', ar: 'شركة' },
  individual: { en: 'Individual', ar: 'فرد' },

  // Signatures
  authorizedSignature: { en: 'Authorized Signature', ar: 'التوقيع المعتمد' },
  lesseeAcknowledgment: { en: 'Lessee Acknowledgment', ar: 'إقرار المستأجر' },
  signedBy: { en: 'Signed by', ar: 'وقع بواسطة' },
  signatureDate: { en: 'Signature Date', ar: 'تاريخ التوقيع' },

  // Boilerplate
  termsHeading: { en: 'Terms & Conditions', ar: 'الشروط والأحكام' },
  quotationDisclaimer: {
    en: 'This quotation is subject to credit approval and signed agreement. Prices are inclusive of UAE VAT at the prevailing rate. Validity expires on the date shown above. All vehicles remain the property of the lessor throughout the lease term.',
    ar: 'يخضع هذا العرض للموافقة على الائتمان والتوقيع على الاتفاقية. الأسعار شاملة لضريبة القيمة المضافة في الإمارات بالنسبة المعمول بها. ينتهي صلاحية العرض في التاريخ المبين أعلاه. تظل جميع المركبات ملكاً للمؤجر طوال فترة الإيجار.',
  },
  generatedBy: { en: 'Generated by Smart Mobility Platform', ar: 'تم الإنشاء بواسطة منصة التنقل الذكي' },

  // Pre-billing
  billingPeriod: { en: 'Billing Period', ar: 'فترة الفوترة' },
  dueDate: { en: 'Due Date', ar: 'تاريخ الاستحقاق' },
  fuelCharges: { en: 'Fuel Charges', ar: 'رسوم الوقود' },
  fineCharges: { en: 'Traffic Fines', ar: 'المخالفات المرورية' },
  overageCharges: { en: 'Mileage Overage', ar: 'تجاوز الكيلومترات' },
  otherCharges: { en: 'Other Charges', ar: 'رسوم أخرى' },
  contractRef: { en: 'Contract Ref.', ar: 'مرجع العقد' },
  reviewWindowNote: {
    en: 'This is a pre-billing statement. Please review and confirm by the due date. Final invoice will follow.',
    ar: 'هذا كشف فوترة مسبق. يرجى المراجعة والتأكيد قبل تاريخ الاستحقاق. ستتبع الفاتورة النهائية.',
  },
  itemisedDetail: { en: 'Itemised Detail', ar: 'التفاصيل المفصلة' },
  description: { en: 'Description', ar: 'الوصف' },
  amount: { en: 'Amount', ar: 'المبلغ' },

  // Invoice
  invoiceNo: { en: 'Invoice No.', ar: 'رقم الفاتورة' },
  issueDate: { en: 'Issue Date', ar: 'تاريخ الإصدار' },
  unitPrice: { en: 'Unit Price', ar: 'سعر الوحدة' },
  taxableSupplies: { en: 'Taxable Supplies', ar: 'التوريدات الخاضعة للضريبة' },
  paymentTerms: { en: 'Payment Terms', ar: 'شروط الدفع' },
  thirtyDays: { en: 'Net 30 Days', ar: 'صافي 30 يوماً' },
  invoiceFooter: {
    en: 'Please remit payment by the due date. For queries, contact our finance team.',
    ar: 'يرجى تسوية الدفع قبل تاريخ الاستحقاق. للاستفسارات، يرجى التواصل مع فريق المالية.',
  },

  // Receipt
  receiptNo: { en: 'Receipt No.', ar: 'رقم الإيصال' },
  receivedDate: { en: 'Received On', ar: 'تاريخ الاستلام' },
  paymentMethod: { en: 'Payment Method', ar: 'طريقة الدفع' },
  paymentType: { en: 'Payment Type', ar: 'نوع الدفع' },
  chequeNo: { en: 'Cheque No.', ar: 'رقم الشيك' },
  bankRef: { en: 'Bank Reference', ar: 'مرجع البنك' },
  amountReceived: { en: 'Amount Received', ar: 'المبلغ المستلم' },
  receivedFrom: { en: 'Received From', ar: 'استلم من' },
  receiptThanks: {
    en: 'Thank you for your payment. This receipt confirms the amount above has been received in full.',
    ar: 'شكراً لكم على الدفع. يؤكد هذا الإيصال استلام المبلغ المذكور أعلاه بالكامل.',
  },
  // Payment types
  pt_DEPOSIT: { en: 'Deposit', ar: 'وديعة' },
  pt_SECURITY: { en: 'Security Deposit', ar: 'تأمين' },
  pt_MONTHLY: { en: 'Monthly Rent', ar: 'إيجار شهري' },
  pt_ADVANCE: { en: 'Advance Payment', ar: 'دفعة مقدمة' },
  pt_PENALTY: { en: 'Penalty', ar: 'غرامة' },
  // Payment methods
  pm_CASH: { en: 'Cash', ar: 'نقد' },
  pm_CHEQUE: { en: 'Cheque', ar: 'شيك' },
  pm_BANK_TRANSFER: { en: 'Bank Transfer', ar: 'تحويل بنكي' },
  pm_CARD: { en: 'Card', ar: 'بطاقة' },

  // Contract / Agreement
  contractNo: { en: 'Contract No.', ar: 'رقم العقد' },
  startDate: { en: 'Start Date', ar: 'تاريخ البدء' },
  endDate: { en: 'End Date', ar: 'تاريخ الانتهاء' },
  termsConditions: { en: 'Terms & Conditions', ar: 'الشروط والأحكام' },
  vehicleSchedule: { en: 'Vehicle Schedule', ar: 'جدول المركبات' },
  licensePlate: { en: 'Plate', ar: 'لوحة' },
  vin: { en: 'VIN', ar: 'رقم الهيكل' },
  lessor: { en: 'Lessor', ar: 'المؤجر' },
  lessee: { en: 'Lessee', ar: 'المستأجر' },
  contractPreamble: {
    en: 'This Lease Agreement is entered into between the Lessor and the Lessee for the lease of vehicle(s) described in the Vehicle Schedule below, on the terms and conditions set out herein.',
    ar: 'تم إبرام عقد الإيجار هذا بين المؤجر والمستأجر لإيجار المركبة (المركبات) الموضحة في جدول المركبات أدناه، بموجب الشروط والأحكام المنصوص عليها هنا.',
  },
  contractTermsBoilerplate: {
    en: '1. Monthly rent is payable in advance by the 1st of each month. Late payments accrue penalties per the schedule above.\n2. Mileage cap and overage rate are as specified. Excess kilometres are billed monthly.\n3. Insurance, maintenance, and driver services are included only where indicated. Otherwise the Lessee is responsible.\n4. Vehicles must be returned in the condition received, fair wear and tear excepted.\n5. Early termination triggers fees per the platform\'s standard schedule.\n6. This agreement is governed by the laws of the United Arab Emirates.',
    ar: '1. الإيجار الشهري مستحق مقدماً في اليوم الأول من كل شهر. تتراكم غرامات على المدفوعات المتأخرة وفقاً للجدول أعلاه.\n2. الحد الأقصى للكيلومترات ومعدل التجاوز كما هو محدد. تُحسب الكيلومترات الزائدة شهرياً.\n3. التأمين والصيانة وخدمات السائق مشمولة فقط حيث يُشار إلى ذلك. وإلا فإن المستأجر يتحمل المسؤولية.\n4. يجب إعادة المركبات بنفس الحالة التي استُلمت بها، باستثناء البلى العادي.\n5. الإنهاء المبكر يستوجب رسوماً وفقاً للجدول القياسي للمنصة.\n6. تخضع هذه الاتفاقية لقوانين دولة الإمارات العربية المتحدة.',
  },
  signature: { en: 'Signature', ar: 'التوقيع' },
  representative: { en: 'Authorized Representative', ar: 'الممثل المعتمد' },

  // Customer account statement
  accountStatement: { en: 'Account Statement', ar: 'كشف حساب' },
  statementPeriod: { en: 'Statement Period', ar: 'فترة الكشف' },
  openingBalance: { en: 'Opening Balance', ar: 'الرصيد الافتتاحي' },
  closingBalance: { en: 'Closing Balance', ar: 'الرصيد الختامي' },
  debit: { en: 'Debit', ar: 'مدين' },
  credit: { en: 'Credit', ar: 'دائن' },
  balance: { en: 'Balance', ar: 'الرصيد' },
  transactionType: { en: 'Type', ar: 'النوع' },
  reference: { en: 'Reference', ar: 'المرجع' },
  noTransactions: { en: 'No transactions in this period.', ar: 'لا توجد معاملات في هذه الفترة.' },
  txn_INVOICE: { en: 'Invoice', ar: 'فاتورة' },
  txn_PAYMENT: { en: 'Payment', ar: 'دفعة' },

  // ── Rent-A-Car specifics ────────────────────────────────────────────────
  rentalAgreement: { en: 'Rental Agreement', ar: 'عقد إيجار سيارة' },
  agreementNo: { en: 'Agreement No.', ar: 'رقم العقد' },
  pickupDate: { en: 'Pickup Date', ar: 'تاريخ الاستلام' },
  dropoffDate: { en: 'Drop-off Date', ar: 'تاريخ الإرجاع' },
  pickupBranch: { en: 'Pickup Branch', ar: 'فرع الاستلام' },
  dropoffBranch: { en: 'Drop-off Branch', ar: 'فرع الإرجاع' },
  dailyRateLabel: { en: 'Daily Rate', ar: 'الإيجار اليومي' },
  totalDays: { en: 'Total Days', ar: 'إجمالي الأيام' },
  mileageIn: { en: 'Mileage at Pickup', ar: 'الكيلومترات عند الاستلام' },
  mileageOut: { en: 'Mileage at Return', ar: 'الكيلومترات عند الإرجاع' },
  fuelIn: { en: 'Fuel at Pickup', ar: 'الوقود عند الاستلام' },
  fuelOut: { en: 'Fuel at Return', ar: 'الوقود عند الإرجاع' },
  rentalVehicle: { en: 'Rental Vehicle', ar: 'المركبة المؤجرة' },
  ancillaries: { en: 'Ancillaries / Add-ons', ar: 'الإضافات' },
  ancillariesTotal: { en: 'Ancillaries total', ar: 'إجمالي الإضافات' },
  insuranceTier: { en: 'Insurance', ar: 'التأمين' },
  rentalCharges: { en: 'Rental Charges', ar: 'رسوم الإيجار' },
  rentalAgreementPreamble: {
    en: 'This Rental Agreement is entered into between the Rental Company (Lessor) and the Renter (Lessee) for the short-term rental of the vehicle described below, on the terms and conditions set out herein.',
    ar: 'تم إبرام عقد الإيجار هذا بين شركة التأجير (المؤجر) والمستأجر لإيجار قصير الأمد للمركبة الموصوفة أدناه، بموجب الشروط والأحكام المنصوص عليها هنا.',
  },
  rentalTermsBoilerplate: {
    en: '1. The vehicle is rented in the condition shown at handover. Any new damage at return is billable per the bodyshop assessment.\n2. Mileage cap and overage rate apply if specified. Excess kilometres are billed at the rate above.\n3. Fuel: vehicle must be returned at the same level shown on this agreement, or refuelled at the prevailing rate.\n4. Cross-border travel requires the appropriate permit and is not permitted without prior written consent.\n5. The renter is responsible for traffic violations, Salik tolls, and parking fines incurred during the rental period.\n6. Late return is charged at hourly rates after the grace period. The vehicle must be returned with valid driving licence and a credit card on file.\n7. Insurance coverage is per the tier selected above. Excess applies for collision damage outside coverage.\n8. This agreement is governed by the laws of the United Arab Emirates.',
    ar: '1. تُؤجر المركبة بالحالة الموضحة عند التسليم. أي ضرر جديد عند الإرجاع يُحسب وفقاً لتقييم ورشة الإصلاح.\n2. يُطبق الحد الأقصى للكيلومترات ومعدل التجاوز إذا تم تحديده. تُحسب الكيلومترات الزائدة بالسعر أعلاه.\n3. الوقود: يجب إعادة المركبة بنفس مستوى الوقود الموضح في هذا العقد، أو إعادة تعبئتها بالسعر السائد.\n4. السفر عبر الحدود يتطلب التصريح المناسب ولا يُسمح به دون موافقة كتابية مسبقة.\n5. المستأجر مسؤول عن المخالفات المرورية ورسوم سالك وغرامات المواقف خلال فترة الإيجار.\n6. الإرجاع المتأخر يُحسب بالساعة بعد فترة السماح. يجب إعادة المركبة مع رخصة قيادة سارية وبطاقة ائتمان في الملف.\n7. تغطية التأمين وفقاً للمستوى المختار أعلاه. يُطبق التحمل على أضرار التصادم خارج التغطية.\n8. تخضع هذه الاتفاقية لقوانين دولة الإمارات العربية المتحدة.',
  },
  renter: { en: 'Renter', ar: 'المستأجر' },
  rentalCompany: { en: 'Rental Company', ar: 'شركة التأجير' },
} as const;

export type PdfStringKey = keyof typeof pdfStrings;

export function t(key: PdfStringKey, lang: Lang): string {
  return pdfStrings[key][lang];
}
