/**
 * Predictive Maintenance Agent — Runner
 * --------------------------------------
 * Queries all active vehicles, computes risk scores, upserts results,
 * and auto-creates work orders for CRITICAL-risk vehicles that don't
 * already have an open "Predictive Maintenance" work order.
 */
import { prisma } from '@/lib/prisma';
import { AgentDefinition, AgentEvent, AgentRunResult, VehicleRiskScore } from '../types';
import { VehicleInput, scoreVehicle } from './scoring';

// ── Data Collection ────────────────────────────────────────────────────────────

interface VehicleRow {
  id: string;
  vehicle_code: string | null;
  make: string | null;
  model: string | null;
  license_plate: string | null;
  purchase_date: string | null;
  odometer_reading: number | null;
}

interface WoRow { vehicle_id: string; open_count: number; recent_count: number; }
interface FuelRow { vehicle_id: string; baseline_l_per_100: number | null; recent_l_per_100: number | null; }
interface ServiceRow { vehicle_id: string; last_service_date: string | null; last_service_odometer: number | null; }

async function fetchVehicles(vehicleId?: string): Promise<VehicleRow[]> {
  const filter = vehicleId
    ? `AND id = '${vehicleId}'`
    : '';
  return prisma.$queryRawUnsafe<VehicleRow[]>(
    `SELECT id, vehicle_code, make, model, license_plate, purchase_date, odometer_reading
     FROM vehicles
     WHERE deleted_at IS NULL
       AND status NOT IN ('INACTIVE','SOLD')
       ${filter}
     ORDER BY created_at DESC
     LIMIT 500`,
  );
}

async function fetchWorkOrderStats(): Promise<WoRow[]> {
  const cutoff = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString();
  return prisma.$queryRawUnsafe<WoRow[]>(
    `SELECT
       vehicle_id,
       COUNT(*) FILTER (WHERE status IN ('OPEN','IN_PROGRESS','PENDING_PARTS')) AS open_count,
       COUNT(*) FILTER (WHERE created_at >= $1)                                 AS recent_count
     FROM fleet_work_orders
     WHERE deleted_at IS NULL
     GROUP BY vehicle_id`,
    cutoff,
  );
}

async function fetchFuelStats(): Promise<FuelRow[]> {
  const cutoff90 = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString();
  const cutoff30 = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString();
  // fuel_efficiency stored in the fuel log as liters + km_driven
  // We compute L/100km = (total_liters / total_km) * 100
  return prisma.$queryRawUnsafe<FuelRow[]>(
    `SELECT
       vehicle_id,
       CASE WHEN SUM(km_driven) FILTER (WHERE fuel_date >= $1 AND km_driven > 0) > 0
            THEN ROUND((SUM(liters) FILTER (WHERE fuel_date >= $1 AND km_driven > 0)
                 / SUM(km_driven) FILTER (WHERE fuel_date >= $1 AND km_driven > 0)) * 100, 2)
            ELSE NULL END AS baseline_l_per_100,
       CASE WHEN SUM(km_driven) FILTER (WHERE fuel_date >= $2 AND km_driven > 0) > 0
            THEN ROUND((SUM(liters) FILTER (WHERE fuel_date >= $2 AND km_driven > 0)
                 / SUM(km_driven) FILTER (WHERE fuel_date >= $2 AND km_driven > 0)) * 100, 2)
            ELSE NULL END AS recent_l_per_100
     FROM fuel_logs
     GROUP BY vehicle_id`,
    cutoff90,
    cutoff30,
  ).catch(() => [] as FuelRow[]); // fuel_logs may be Prisma-managed; graceful fallback
}

async function fetchServiceHistory(): Promise<ServiceRow[]> {
  // Last completed maintenance lifecycle event per vehicle
  return prisma.$queryRawUnsafe<ServiceRow[]>(
    `SELECT DISTINCT ON (vehicle_id)
       vehicle_id,
       event_date::TEXT AS last_service_date,
       odometer_reading AS last_service_odometer
     FROM fleet_lifecycle_events
     WHERE event_type IN ('MAINTENANCE','SERVICE','REPAIR')
       AND status = 'COMPLETED'
     ORDER BY vehicle_id, event_date DESC`,
  ).catch(() => [] as ServiceRow[]);
}

async function getExistingPredictiveWOs(): Promise<Set<string>> {
  const rows = await prisma.$queryRawUnsafe<{ vehicle_id: string }[]>(
    `SELECT DISTINCT vehicle_id FROM fleet_work_orders
     WHERE title ILIKE '%predictive maintenance%'
       AND status IN ('OPEN','IN_PROGRESS','PENDING_PARTS')
       AND deleted_at IS NULL`,
  ).catch(() => []);
  return new Set(rows.map((r) => r.vehicle_id));
}

// ── Work Order Auto-Creation ───────────────────────────────────────────────────
async function autoCreateWorkOrder(score: VehicleRiskScore): Promise<string | null> {
  try {
    const id = crypto.randomUUID();
    const now = new Date().toISOString();
    const priority = score.riskLevel === 'CRITICAL' ? 'CRITICAL' : 'HIGH';
    const title = `[Predictive Maintenance] ${score.make ?? ''} ${score.model ?? ''} — ${score.riskLevel} Risk`;
    const description =
      `Auto-generated by Predictive Maintenance Agent (score: ${score.riskScore.toFixed(3)}).\n` +
      `Risk Level: ${score.riskLevel} | Predicted Window: ${score.predictedFailureWindow}\n` +
      `Action: ${score.recommendedAction}\n` +
      `Top factors: Service overdue ${Math.round(score.factors.serviceOverdue * 100)}% | ` +
      `Fuel anomaly ${Math.round(score.factors.fuelAnomalyScore * 100)}% | ` +
      `Open WOs: ${score.factors.openWorkOrders}`;

    await prisma.$executeRawUnsafe(
      `INSERT INTO fleet_work_orders (
         id, vehicle_id, title, description, status, priority,
         work_order_type, requested_by, created_at, updated_at
       ) VALUES ($1,$2,$3,$4,'OPEN',$5,'PREVENTIVE','Predictive Maintenance Agent',$6,$7)`,
      id,
      score.vehicleId,
      title,
      description,
      priority,
      now,
      now,
    );
    return id;
  } catch {
    return null; // non-fatal — log but don't fail the agent run
  }
}

// ── Upsert Risk Score ──────────────────────────────────────────────────────────
async function upsertRiskScore(score: VehicleRiskScore, runId: string, woId?: string | null): Promise<void> {
  await prisma.$executeRawUnsafe(
    `INSERT INTO fleet_risk_scores (
       vehicle_id, vehicle_code, make, model, license_plate,
       risk_score, risk_level, factors, recommended_action,
       predicted_failure_window, auto_work_order_id, agent_run_id, scored_at
     ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW())
     ON CONFLICT (vehicle_id) DO UPDATE SET
       vehicle_code = EXCLUDED.vehicle_code,
       make = EXCLUDED.make,
       model = EXCLUDED.model,
       license_plate = EXCLUDED.license_plate,
       risk_score = EXCLUDED.risk_score,
       risk_level = EXCLUDED.risk_level,
       factors = EXCLUDED.factors,
       recommended_action = EXCLUDED.recommended_action,
       predicted_failure_window = EXCLUDED.predicted_failure_window,
       auto_work_order_id = COALESCE(EXCLUDED.auto_work_order_id, fleet_risk_scores.auto_work_order_id),
       agent_run_id = EXCLUDED.agent_run_id,
       scored_at = NOW()`,
    score.vehicleId,
    score.vehicleCode,
    score.make,
    score.model,
    score.licensePlate,
    score.riskScore,
    score.riskLevel,
    JSON.stringify(score.factors),
    score.recommendedAction,
    score.predictedFailureWindow,
    woId ?? null,
    runId,
  );
}

// ── Agent Runner ───────────────────────────────────────────────────────────────
async function run(event: AgentEvent): Promise<AgentRunResult> {
  const started = Date.now();
  const runId = crypto.randomUUID();

  // Persist a placeholder run ID we reference in upserts
  await prisma.$executeRawUnsafe(
    `INSERT INTO agent_runs (id, agent_id, tenant_id, event_type, entity_id, status, created_at)
     VALUES ($1,'predictive-maintenance',$2,$3,$4,'RUNNING',NOW())`,
    runId,
    event.tenant_id,
    event.event_type,
    event.entity_id ?? null,
  ).catch(() => {/* schema may not exist yet on very first call */});

  const [vehicles, woStats, fuelStats, serviceHistory, existingPredWOs] = await Promise.all([
    fetchVehicles(event.entity_id),
    fetchWorkOrderStats(),
    fetchFuelStats(),
    fetchServiceHistory(),
    getExistingPredictiveWOs(),
  ]);

  // Build lookup maps
  const woMap      = new Map(woStats.map((r)  => [r.vehicle_id, r]));
  const fuelMap    = new Map(fuelStats.map((r) => [r.vehicle_id, r]));
  const serviceMap = new Map(serviceHistory.map((r) => [r.vehicle_id, r]));

  // Fleet-wide average WOs per 90 days (for relative comparison)
  const totalWo90 = woStats.reduce((s, r) => s + Number(r.recent_count ?? 0), 0);
  const fleetAvgWo = vehicles.length > 0 ? totalWo90 / vehicles.length : 0;

  const now = Date.now();
  const scores: VehicleRiskScore[] = [];
  let actionsCreated = 0;

  for (const v of vehicles) {
    const wo      = woMap.get(v.id);
    const fuel    = fuelMap.get(v.id);
    const svc     = serviceMap.get(v.id);

    // Days & km since last service
    const lastSvcDate = svc?.last_service_date ? new Date(svc.last_service_date) : null;
    const daysSinceLastService = lastSvcDate
      ? Math.floor((now - lastSvcDate.getTime()) / (1000 * 60 * 60 * 24))
      : SERVICE_INTERVAL_DAYS; // assume overdue if no history

    const currentOdometer = Number(v.odometer_reading ?? 0);
    const lastSvcOdometer = Number(svc?.last_service_odometer ?? 0);
    const kmSinceLastService = Math.max(currentOdometer - lastSvcOdometer, 0);

    const input: VehicleInput = {
      id:                 v.id,
      vehicleCode:        v.vehicle_code ?? '',
      make:               v.make ?? '',
      model:              v.model ?? '',
      licensePlate:       v.license_plate ?? '',
      purchaseDate:       v.purchase_date,
      odometerReading:    currentOdometer,
      daysSinceLastService,
      kmSinceLastService,
      baselineFuelLper100: fuel ? Number(fuel.baseline_l_per_100) : null,
      recentFuelLper100:   fuel ? Number(fuel.recent_l_per_100)   : null,
      openWorkOrders:      Number(wo?.open_count   ?? 0),
      workOrdersLast90Days: Number(wo?.recent_count ?? 0),
    };

    const score = scoreVehicle(input, fleetAvgWo);
    scores.push(score);

    // Auto-create WO for CRITICAL vehicles without an existing predictive WO
    let woId: string | null = null;
    if (score.riskLevel === 'CRITICAL' && !existingPredWOs.has(v.id)) {
      woId = await autoCreateWorkOrder(score);
      if (woId) actionsCreated++;
    }

    await upsertRiskScore(score, runId, woId);
  }

  const durationMs = Date.now() - started;

  // Update the run record with final stats
  await prisma.$executeRawUnsafe(
    `UPDATE agent_runs SET
       status='COMPLETED', items_processed=$1, actions_created=$2,
       duration_ms=$3, output=$4
     WHERE id=$5`,
    scores.length,
    actionsCreated,
    durationMs,
    JSON.stringify({ summary: buildSummary(scores), scored: scores.length }),
    runId,
  ).catch(() => {});

  return {
    agentId:        'predictive-maintenance',
    tenantId:       event.tenant_id,
    eventType:      event.event_type,
    entityId:       event.entity_id,
    status:         'COMPLETED',
    durationMs,
    itemsProcessed: scores.length,
    actionsCreated,
    output: {
      summary: buildSummary(scores),
      scores,
    },
  };
}

function buildSummary(scores: VehicleRiskScore[]) {
  return {
    total:    scores.length,
    critical: scores.filter((s) => s.riskLevel === 'CRITICAL').length,
    high:     scores.filter((s) => s.riskLevel === 'HIGH').length,
    medium:   scores.filter((s) => s.riskLevel === 'MEDIUM').length,
    low:      scores.filter((s) => s.riskLevel === 'LOW').length,
    avgScore: scores.length > 0
      ? parseFloat((scores.reduce((a, s) => a + s.riskScore, 0) / scores.length).toFixed(3))
      : 0,
  };
}

const SERVICE_INTERVAL_DAYS = 90;

export const PREDICTIVE_MAINTENANCE_AGENT: AgentDefinition = {
  id:          'predictive-maintenance',
  name:        'Predictive Maintenance Agent',
  description: '5-factor statistical model that scores all vehicles and auto-creates work orders for critical risks.',
  version:     '1.0.0',
  agentType:   'BATCH',
  subscribedEvents: [
    'vehicle.odometer_updated',
    'vehicle.fuel_log_added',
    'vehicle.work_order_created',
    'manual.trigger',
    'schedule.nightly',
  ],
  supportsEntityScan: true,
  run,
};
